#if UNITY_EDITOR && ANNULUS_CODEGEN && MODULE_CORE_MVVM_ADAPTERS_GENERATOR

using System;
using Module.Core.CodeGen;
using UnityCodeGen;
using UnityEngine;

namespace Module.Core.Extended.Editor.Mvvm.ViewBinding.Adapters.Unity
{
    [Generator]
    internal class AnyResoucesAdaptersGenerator : ICodeGenerator
    {
        private readonly static string[] s_unityTypes = new string[] {
            nameof(Sprite),
            nameof(GameObject),
            nameof(AudioClip),
        };

        public void Execute(GeneratorContext context)
        {
            var nameofGenerator = nameof(AnyResoucesAdaptersGenerator);

            if (CodeGenAPI.TryGetOutputFolderPath(nameofGenerator, out var outputPath) == false)
            {
                context.OverrideFolderPath("Assets");
                return;
            }

            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameofGenerator);
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System;
using Module.Core.Mvvm.ViewBinding;
using UnityEngine;
");

            p.PrintLine("namespace Module.Core.Extended.Mvvm.ViewBinding.Adapters.Unity");
            p.OpenScope();
            {
                var unityTypes = s_unityTypes.AsSpan();

                for (var i = 0; i < unityTypes.Length; i++)
                {
                    var type = unityTypes[i];

                    p.PrintLine($"[Serializable]");
                    p.PrintLine($"[Label(\"Resources.Load<{type}>(string)\", \"Default\")]");
                    p.PrintLine($"[Adapter(sourceType: typeof(string), destType: typeof({type}), order: 0)]");
                    p.PrintLine($"public sealed class {type}ResorcesAdapter : ResourcesAdapter<{type}> {{ }}");
                    p.PrintEndLine();
                }
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(outputPath);
            context.AddCode($"AnyResoucesAdapters.gen.cs", p.Result);
        }
    }
}

#endif
