/// <auto-generated>
///*************************************************************///
///                                                             ///
/// This file is auto-generated by AnyResoucesAdaptersGenerator ///
///                 DO NOT manually modify it!                  ///
///                                                             ///
///*************************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using Module.Core.Mvvm.ViewBinding;
using UnityEngine;

namespace Module.Core.Extended.Mvvm.ViewBinding.Adapters.Unity
{
    [Serializable]
    [Label("Resources.Load<Sprite>(string)", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(Sprite), order: 0)]
    public sealed class SpriteResorcesAdapter : ResourcesAdapter<Sprite> { }

    [Serializable]
    [Label("Resources.Load<GameObject>(string)", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(GameObject), order: 0)]
    public sealed class GameObjectResorcesAdapter : ResourcesAdapter<GameObject> { }

    [Serializable]
    [Label("Resources.Load<AudioClip>(string)", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(AudioClip), order: 0)]
    public sealed class AudioClipResorcesAdapter : ResourcesAdapter<AudioClip> { }

}

