/// <auto-generated>
///****************************************************************///
///                                                                ///
/// This file is auto-generated by AnyUnionOfUnityObjectsGenerator ///
///                   DO NOT manually modify it!                   ///
///                                                                ///
///****************************************************************///
/// </auto-generated>

#pragma warning disable

using Module.Core.Unions;
using UnityEngine;

namespace Module.Core.Extended.Mvvm.ViewBinding.Adapters.Unity
{
    public readonly partial struct Union_Sprite : IUnion<Sprite> { }

    public readonly partial struct Union_GameObject : IUnion<GameObject> { }

    public readonly partial struct Union_AudioClip : IUnion<AudioClip> { }

}
