namespace EncosyTower.Modules.SourceGen
{
    public static class UnionTypeKindExtensions
    {
        public static bool IsNativeUnionType(this UnionTypeKind value)
            => value switch {
                UnionTypeKind.Bool => true,
                UnionTypeKind.Byte => true,
                UnionTypeKind.SByte => true,
                UnionTypeKind.Char => true,
                UnionTypeKind.Double => true,
                UnionTypeKind.Float => true,
                UnionTypeKind.Int => true,
                UnionTypeKind.UInt => true,
                UnionTypeKind.Long => true,
                UnionTypeKind.ULong => true,
                UnionTypeKind.Short => true,
                UnionTypeKind.UShort => true,
                UnionTypeKind.String => true,
                UnionTypeKind.Object => true,
                _ => false,
            };

        public static UnionTypeKind ToUnionType(this string value)
            => value switch {
                "bool" => UnionTypeKind.Bool,
                "byte" => UnionTypeKind.Byte,
                "sbyte" => UnionTypeKind.SByte,
                "char" => UnionTypeKind.Char,
                "double" => UnionTypeKind.Double,
                "float" => UnionTypeKind.Float,
                "int" => UnionTypeKind.Int,
                "uint" => UnionTypeKind.UInt,
                "long" => UnionTypeKind.Long,
                "ulong" => UnionTypeKind.ULong,
                "short" => UnionTypeKind.Short,
                "ushort" => UnionTypeKind.UShort,
                "string" => UnionTypeKind.String,
                "object" => UnionTypeKind.Object,
                "Boolean" => UnionTypeKind.Bool,
                "Byte" => UnionTypeKind.Byte,
                "SByte" => UnionTypeKind.SByte,
                "Char" => UnionTypeKind.Char,
                "Double" => UnionTypeKind.Double,
                "Single" => UnionTypeKind.Float,
                "Int32" => UnionTypeKind.Int,
                "UInt32" => UnionTypeKind.UInt,
                "Int64" => UnionTypeKind.Long,
                "UInt64" => UnionTypeKind.ULong,
                "Int16" => UnionTypeKind.Short,
                "UInt16" => UnionTypeKind.UShort,
                "String" => UnionTypeKind.String,
                "Object" => UnionTypeKind.Object,
                "System.Boolean" => UnionTypeKind.Bool,
                "System.Byte" => UnionTypeKind.Byte,
                "System.SByte" => UnionTypeKind.SByte,
                "System.Char" => UnionTypeKind.Char,
                "System.Double" => UnionTypeKind.Double,
                "System.Single" => UnionTypeKind.Float,
                "System.Int32" => UnionTypeKind.Int,
                "System.UInt32" => UnionTypeKind.UInt,
                "System.Int64" => UnionTypeKind.Long,
                "System.UInt64" => UnionTypeKind.ULong,
                "System.Int16" => UnionTypeKind.Short,
                "System.UInt16" => UnionTypeKind.UShort,
                "System.String" => UnionTypeKind.String,
                "System.Object" => UnionTypeKind.Object,
                "global::System.Boolean" => UnionTypeKind.Bool,
                "global::System.Byte" => UnionTypeKind.Byte,
                "global::System.SByte" => UnionTypeKind.SByte,
                "global::System.Char" => UnionTypeKind.Char,
                "global::System.Double" => UnionTypeKind.Double,
                "global::System.Single" => UnionTypeKind.Float,
                "global::System.Int32" => UnionTypeKind.Int,
                "global::System.UInt32" => UnionTypeKind.UInt,
                "global::System.Int64" => UnionTypeKind.Long,
                "global::System.UInt64" => UnionTypeKind.ULong,
                "global::System.Int16" => UnionTypeKind.Short,
                "global::System.UInt16" => UnionTypeKind.UShort,
                "global::System.String" => UnionTypeKind.String,
                "global::System.Object" => UnionTypeKind.Object,
                _ => UnionTypeKind.Undefined,
            };
    }
}
