namespace EncosyTower.SourceGen.Tests;

/// <summary>
/// Holds Unity DLL path constants resolved at build time.
/// Real values are injected by <c>UnityDllPaths.g.cs</c>, which is generated by the
/// <c>GenerateUnityDllPaths</c> MSBuild target and deleted after the build completes.
/// When the generated file is absent the fields default to empty values.
/// </summary>
internal static partial class UnityDllPaths
{
    /// <summary>
    /// Full paths of all required Unity DLLs, verified to exist at build time.
    /// </summary>
    public static readonly string[] All;

    /// <summary>
    /// Absolute path to the Unity Engine modules folder (contains UnityEngine.CoreModule.dll, etc.).
    /// </summary>
    public static readonly string UnityModulesPath;

    /// <summary>
    /// Absolute path to the Unity project's ScriptAssemblies folder (contains compiled package/asset DLLs).
    /// </summary>
    public static readonly string UnityScriptAssembliesPath;

    static UnityDllPaths()
    {
        var all = Array.Empty<string>();
        var unityModulesPath = string.Empty;
        var unityScriptAssembliesPath = string.Empty;

        InitAll(ref all);
        InitUnityModulesPath(ref unityModulesPath);
        InitUnityScriptAssembliesPath(ref unityScriptAssembliesPath);

        All = all;
        UnityModulesPath = unityModulesPath;
        UnityScriptAssembliesPath = unityScriptAssembliesPath;
    }

    /// <summary>I
    /// mplemented by the generated <c>UnityDllPaths.g.cs</c> to supply all DLL paths.
    /// </summary>
    static partial void InitAll(ref string[] value);

    /// <summary>
    /// Implemented by the generated <c>UnityDllPaths.g.cs</c> to supply the real path.
    /// </summary>
    static partial void InitUnityModulesPath(ref string value);

    /// <summary>
    /// Implemented by the generated <c>UnityDllPaths.g.cs</c> to supply the real path.
    /// </summary>
    static partial void InitUnityScriptAssembliesPath(ref string value);
}
