using System.Collections.Generic;

namespace EncosyTower.Mvvm.ComponentModel
{
    /// <summary>
    /// Defines the interface for an observable object, which is responsible for managing
    /// the notification of property changes and command state changes in a view model.
    /// </summary>
    /// <remarks>
    /// The <see cref="IObservableObject"/> interface is designed to be implemented by classes
    /// that are annotated with the <see cref="ObservableObjectAttribute"/>.
    /// Its details will be generated by a source generator.
    /// </remarks>
    /// <seealso cref="EncosyTower.Mvvm.ComponentModel.ObservablePropertyAttribute"/>
    /// <seealso cref="EncosyTower.Mvvm.Input.RelayCommandAttribute"/>
    public interface IObservableObject
    {
        public bool TryGetMemberObservableObject(Queue<string> names, out IObservableObject result)
        {
            result = default;
            return false;
        }
    }
}
