#if UNITY_MATHEMATICS

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To update the generation of this file, modify and re-run Unity.Mathematics.CodeGen.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace Unity.Mathematics
{
    using static Unity.Mathematics.math;

    /// <summary>A 2 component vector of shorts.</summary>
    [DebuggerTypeProxy(typeof(short2.DebuggerProxy))]
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct short2 : System.IEquatable<short2>, IFormattable
    {
        /// <summary>x component of the vector.</summary>
        public short x;
        /// <summary>y component of the vector.</summary>
        public short y;


        /// <summary>Constructs a short2 vector from two short values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public short2(short x, short y)
        {
            this.x = x;
            this.y = y;
        }

        /// <summary>Constructs a short2 vector from two short values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private short2(int x, int y)
        {
            this.x = (short)x;
            this.y = (short)y;
        }

        /// <summary>Constructs a short2 vector from a short2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public short2(short2 xy)
        {
            this.x = xy.x;
            this.y = xy.y;
        }

        /// <summary>Constructs a short2 vector from a single short value by assigning it to every component.</summary>
        /// <param name="v">short to convert to short2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public short2(short v)
        {
            this.x = v;
            this.y = v;
        }


        /// <summary>Implicitly converts a single short value to a short2 vector by assigning it to every component.</summary>
        /// <param name="v">short to convert to short2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator short2(short v) { return new short2(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise multiplication.</param>
        /// <returns>short2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator * (short2 lhs, short2 rhs) { return new short2 (lhs.x * rhs.x, lhs.y * rhs.y); }

        /// <summary>Returns the result of a componentwise multiplication operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise multiplication.</param>
        /// <returns>short2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator * (short2 lhs, short rhs) { return new short2 (lhs.x * rhs, lhs.y * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise multiplication.</param>
        /// <returns>short2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator * (short lhs, short2 rhs) { return new short2 (lhs * rhs.x, lhs * rhs.y); }


        /// <summary>Returns the result of a componentwise addition operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise addition.</param>
        /// <returns>short2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator + (short2 lhs, short2 rhs) { return new short2 (lhs.x + rhs.x, lhs.y + rhs.y); }

        /// <summary>Returns the result of a componentwise addition operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise addition.</param>
        /// <returns>short2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator + (short2 lhs, short rhs) { return new short2 (lhs.x + rhs, lhs.y + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise addition.</param>
        /// <returns>short2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator + (short lhs, short2 rhs) { return new short2 (lhs + rhs.x, lhs + rhs.y); }


        /// <summary>Returns the result of a componentwise subtraction operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise subtraction.</param>
        /// <returns>short2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator - (short2 lhs, short2 rhs) { return new short2 (lhs.x - rhs.x, lhs.y - rhs.y); }

        /// <summary>Returns the result of a componentwise subtraction operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise subtraction.</param>
        /// <returns>short2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator - (short2 lhs, short rhs) { return new short2 (lhs.x - rhs, lhs.y - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise subtraction.</param>
        /// <returns>short2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator - (short lhs, short2 rhs) { return new short2 (lhs - rhs.x, lhs - rhs.y); }


        /// <summary>Returns the result of a componentwise division operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise division.</param>
        /// <returns>short2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator / (short2 lhs, short2 rhs) { return new short2 (lhs.x / rhs.x, lhs.y / rhs.y); }

        /// <summary>Returns the result of a componentwise division operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise division.</param>
        /// <returns>short2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator / (short2 lhs, short rhs) { return new short2 (lhs.x / rhs, lhs.y / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise division.</param>
        /// <returns>short2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator / (short lhs, short2 rhs) { return new short2 (lhs / rhs.x, lhs / rhs.y); }


        /// <summary>Returns the result of a componentwise modulus operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise modulus.</param>
        /// <returns>short2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator % (short2 lhs, short2 rhs) { return new short2 (lhs.x % rhs.x, lhs.y % rhs.y); }

        /// <summary>Returns the result of a componentwise modulus operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise modulus.</param>
        /// <returns>short2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator % (short2 lhs, short rhs) { return new short2 (lhs.x % rhs, lhs.y % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise modulus.</param>
        /// <returns>short2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator % (short lhs, short2 rhs) { return new short2 (lhs % rhs.x, lhs % rhs.y); }


        /// <summary>Returns the result of a componentwise increment operation on a short2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>short2 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator ++ (short2 val) { return new short2 (++val.x, ++val.y); }


        /// <summary>Returns the result of a componentwise decrement operation on a short2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>short2 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator -- (short2 val) { return new short2 (--val.x, --val.y); }


        /// <summary>Returns the result of a componentwise less than operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (short2 lhs, short2 rhs) { return new bool2 (lhs.x < rhs.x, lhs.y < rhs.y); }

        /// <summary>Returns the result of a componentwise less than operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (short2 lhs, short rhs) { return new bool2 (lhs.x < rhs, lhs.y < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (short lhs, short2 rhs) { return new bool2 (lhs < rhs.x, lhs < rhs.y); }


        /// <summary>Returns the result of a componentwise less or equal operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (short2 lhs, short2 rhs) { return new bool2 (lhs.x <= rhs.x, lhs.y <= rhs.y); }

        /// <summary>Returns the result of a componentwise less or equal operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (short2 lhs, short rhs) { return new bool2 (lhs.x <= rhs, lhs.y <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (short lhs, short2 rhs) { return new bool2 (lhs <= rhs.x, lhs <= rhs.y); }


        /// <summary>Returns the result of a componentwise greater than operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (short2 lhs, short2 rhs) { return new bool2 (lhs.x > rhs.x, lhs.y > rhs.y); }

        /// <summary>Returns the result of a componentwise greater than operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (short2 lhs, short rhs) { return new bool2 (lhs.x > rhs, lhs.y > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (short lhs, short2 rhs) { return new bool2 (lhs > rhs.x, lhs > rhs.y); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (short2 lhs, short2 rhs) { return new bool2 (lhs.x >= rhs.x, lhs.y >= rhs.y); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (short2 lhs, short rhs) { return new bool2 (lhs.x >= rhs, lhs.y >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (short lhs, short2 rhs) { return new bool2 (lhs >= rhs.x, lhs >= rhs.y); }


        /// <summary>Returns the result of a componentwise unary minus operation on a short2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>short2 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator - (short2 val) { return new short2 (-val.x, -val.y); }


        /// <summary>Returns the result of a componentwise unary plus operation on a short2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>short2 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator + (short2 val) { return new short2 (+val.x, +val.y); }


        /// <summary>Returns the result of a componentwise left shift operation on a short2 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to left shift.</param>
        /// <param name="n">The number of bits to left shift.</param>
        /// <returns>The result of the componentwise left shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator << (short2 x, int n) { return new short2 (x.x << n, x.y << n); }

        /// <summary>Returns the result of a componentwise right shift operation on a short2 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to right shift.</param>
        /// <param name="n">The number of bits to right shift.</param>
        /// <returns>The result of the componentwise right shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator >> (short2 x, int n) { return new short2 (x.x >> n, x.y >> n); }

        /// <summary>Returns the result of a componentwise equality operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (short2 lhs, short2 rhs) { return new bool2 (lhs.x == rhs.x, lhs.y == rhs.y); }

        /// <summary>Returns the result of a componentwise equality operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (short2 lhs, short rhs) { return new bool2 (lhs.x == rhs, lhs.y == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (short lhs, short2 rhs) { return new bool2 (lhs == rhs.x, lhs == rhs.y); }


        /// <summary>Returns the result of a componentwise not equal operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (short2 lhs, short2 rhs) { return new bool2 (lhs.x != rhs.x, lhs.y != rhs.y); }

        /// <summary>Returns the result of a componentwise not equal operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (short2 lhs, short rhs) { return new bool2 (lhs.x != rhs, lhs.y != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (short lhs, short2 rhs) { return new bool2 (lhs != rhs.x, lhs != rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise not operation on a short2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise bitwise not.</param>
        /// <returns>short2 result of the componentwise bitwise not.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator ~ (short2 val) { return new short2 (~val.x, ~val.y); }


        /// <summary>Returns the result of a componentwise bitwise and operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise and.</param>
        /// <returns>short2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator & (short2 lhs, short2 rhs) { return new short2 (lhs.x & rhs.x, lhs.y & rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise bitwise and.</param>
        /// <returns>short2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator & (short2 lhs, short rhs) { return new short2 (lhs.x & rhs, lhs.y & rhs); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise and.</param>
        /// <returns>short2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator & (short lhs, short2 rhs) { return new short2 (lhs & rhs.x, lhs & rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise or operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise or.</param>
        /// <returns>short2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator | (short2 lhs, short2 rhs) { return new short2 (lhs.x | rhs.x, lhs.y | rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise bitwise or.</param>
        /// <returns>short2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator | (short2 lhs, short rhs) { return new short2 (lhs.x | rhs, lhs.y | rhs); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise or.</param>
        /// <returns>short2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator | (short lhs, short2 rhs) { return new short2 (lhs | rhs.x, lhs | rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on two short2 vectors.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>short2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator ^ (short2 lhs, short2 rhs) { return new short2 (lhs.x ^ rhs.x, lhs.y ^ rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a short2 vector and a short value.</summary>
        /// <param name="lhs">Left hand side short2 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side short to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>short2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator ^ (short2 lhs, short rhs) { return new short2 (lhs.x ^ rhs, lhs.y ^ rhs); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a short value and a short2 vector.</summary>
        /// <param name="lhs">Left hand side short to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side short2 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>short2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 operator ^ (short lhs, short2 rhs) { return new short2 (lhs ^ rhs.x, lhs ^ rhs.y); }




        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(x, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short4(y, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short3(y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short2(x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public short2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new short2(y, y); }
        }



        /// <summary>Returns the short element at a specified index.</summary>
        unsafe public short this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (short2* array = &this) { return ((short*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (short* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the short2 is equal to a given short2, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(short2 rhs) { return x == rhs.x && y == rhs.y; }

        /// <summary>Returns true if the short2 is equal to a given short2, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is short2 converted && Equals(converted); }


        /// <summary>Returns a hash code for the short2.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)umath.hash(this); }


        /// <summary>Returns a string representation of the short2.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("short2({0}, {1})", x, y);
        }

        /// <summary>Returns a string representation of the short2 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("short2({0}, {1})", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public short x;
            public short y;
            public DebuggerProxy(short2 v)
            {
                x = v.x;
                y = v.y;
            }
        }

    }

    public static partial class umath
    {
        /// <summary>Returns a short2 vector constructed from two short values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <returns>short2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 short2(short x, short y) { return new short2(x, y); }

        /// <summary>Returns a short2 vector constructed from a short2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <returns>short2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 short2(short2 xy) { return new short2(xy); }

        /// <summary>Returns a short2 vector constructed from a single short value by assigning it to every component.</summary>
        /// <param name="v">short to convert to short2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 short2(short v) { return new short2(v); }

        /// <summary>Returns a uint hash code of a short2 vector.</summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(short2 v)
        {
            return csum(asuint(v) * uint2(0x83B58237u, 0x833E3E29u)) + 0xA9D919BFu;
        }

        /// <summary>
        /// Returns a uint2 vector hash code of a short2 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint2 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint2 hashwide(short2 v)
        {
            return (asuint(v) * uint2(0xC3EC1D97u, 0xB8B208C7u)) + 0x5D3ED947u;
        }

        /// <summary>Returns the result of specified shuffling of the components from two short2 vectors into a short value.</summary>
        /// <param name="left">short2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">short2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting short.</param>
        /// <returns>short result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short shuffle(short2 left, short2 right, ShuffleComponent x)
        {
            return select_shuffle_component(left, right, x);
        }

        /// <summary>Returns the result of specified shuffling of the components from two short2 vectors into a short2 vector.</summary>
        /// <param name="left">short2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">short2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting short2 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting short2 y component.</param>
        /// <returns>short2 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short2 shuffle(short2 left, short2 right, ShuffleComponent x, ShuffleComponent y)
        {
            return short2(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y));
        }

        /// <summary>Returns the result of specified shuffling of the components from two short2 vectors into a short3 vector.</summary>
        /// <param name="left">short2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">short2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting short3 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting short3 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting short3 z component.</param>
        /// <returns>short3 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short3 shuffle(short2 left, short2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z)
        {
            return short3(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z));
        }

        /// <summary>Returns the result of specified shuffling of the components from two short2 vectors into a short4 vector.</summary>
        /// <param name="left">short2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">short2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting short4 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting short4 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting short4 z component.</param>
        /// <param name="w">The ShuffleComponent to use when setting the resulting short4 w component.</param>
        /// <returns>short4 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short4 shuffle(short2 left, short2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z, ShuffleComponent w)
        {
            return short4(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z),
                select_shuffle_component(left, right, w));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static short select_shuffle_component(short2 a, short2 b, ShuffleComponent component)
        {
            switch(component)
            {
                case ShuffleComponent.LeftX:
                    return a.x;
                case ShuffleComponent.LeftY:
                    return a.y;
                case ShuffleComponent.RightX:
                    return b.x;
                case ShuffleComponent.RightY:
                    return b.y;
                default:
                    throw new System.ArgumentException("Invalid shuffle component: " + component);
            }
        }
    }
}

#endif
