using System;

namespace Module.Core.Mvvm.ViewBinding.SourceGen
{
    /// <summary>
    /// An attribute that indicates that a given binding property field is generated by the Binder generator.
    /// </summary>
    /// <remarks>
    /// This attribute is not intended to be used directly by user code to decorate user-defined properties.
    /// <br/>
    /// However, it can be used in other contexts, such as reflection.
    /// </remarks>
    /// <seealso cref="BindingProperty"/>
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class GeneratedBindingPropertyAttribute : Attribute
    {
        public string MethodName { get; }

        public Type ArgumentType { get; }

        public GeneratedBindingPropertyAttribute(string methodName, Type argumentType)
        {
            this.MethodName = methodName;
            this.ArgumentType = argumentType;
        }
    }
}
