using System;

namespace EncosyTower.Modules.Mvvm.ViewBinding.SourceGen
{
    /// <summary>
    /// An attribute that indicates that a given field is generated by the Binder generator.
    /// </summary>
    /// <remarks>
    /// This attribute is not intended to be used directly by user code to decorate user-defined properties.
    /// <br/>
    /// However, it can be used in other contexts, such as reflection.
    /// </remarks>
    /// <seealso cref="Converter"/>
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class GeneratedConverterAttribute : Attribute
    {
        public string ForMemberName { get; }

        public Type ForMemberType { get; }

        public GeneratedConverterAttribute(string forMemberName, Type forMemberType)
        {
            this.ForMemberName = forMemberName;
            this.ForMemberType = forMemberType;
        }
    }
}
