using System;

namespace EncosyTower.Databases.SourceGen
{
    /// <summary>
    /// An attribute that indicates that a given constant is generated by the Database generator.
    /// </summary>
    /// <remarks>
    /// This attribute is not intended to be used directly by user code to annotate user-defined properties.
    /// <br/>
    /// However, it can be used in other contexts, such as reflection.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class GeneratedAssetNameConstantAttribute : Attribute { }
}
