/// <auto-generated>
///**************************************************************///
///                                                              ///
/// This file is auto-generated by StatSingleExtensionsGenerator ///
///                  DO NOT manually modify it!                  ///
///                                                              ///
///**************************************************************///
/// </auto-generated>

#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;

namespace EncosyTower.Entities.Stats
{
    public static partial class StatSingleValueExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool> ToStatSingle(this bool value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool2> ToStatSingle(this bool2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool2x2> ToStatSingle(this bool2x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool2x3> ToStatSingle(this bool2x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool2x4> ToStatSingle(this bool2x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool3> ToStatSingle(this bool3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool3x2> ToStatSingle(this bool3x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool3x3> ToStatSingle(this in bool3x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool3x4> ToStatSingle(this in bool3x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool4> ToStatSingle(this bool4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool4x2> ToStatSingle(this bool4x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool4x3> ToStatSingle(this in bool4x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool4x4> ToStatSingle(this in bool4x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<byte> ToStatSingle(this byte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double> ToStatSingle(this double value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double2> ToStatSingle(this in double2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double2x2> ToStatSingle(this in double2x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double2x3> ToStatSingle(this in double2x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double2x4> ToStatSingle(this in double2x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double3> ToStatSingle(this in double3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double3x2> ToStatSingle(this in double3x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double3x3> ToStatSingle(this in double3x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double3x4> ToStatSingle(this in double3x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double4> ToStatSingle(this in double4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double4x2> ToStatSingle(this in double4x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double4x3> ToStatSingle(this in double4x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double4x4> ToStatSingle(this in double4x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float> ToStatSingle(this float value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float2> ToStatSingle(this float2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float2x2> ToStatSingle(this in float2x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float2x3> ToStatSingle(this in float2x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float2x4> ToStatSingle(this in float2x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float3> ToStatSingle(this in float3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float3x2> ToStatSingle(this in float3x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float3x3> ToStatSingle(this in float3x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float3x4> ToStatSingle(this in float3x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float4> ToStatSingle(this in float4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float4x2> ToStatSingle(this in float4x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float4x3> ToStatSingle(this in float4x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float4x4> ToStatSingle(this in float4x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half> ToStatSingle(this half value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half2> ToStatSingle(this half2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half3> ToStatSingle(this half3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half4> ToStatSingle(this half4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int> ToStatSingle(this int value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int2> ToStatSingle(this int2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int2x2> ToStatSingle(this in int2x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int2x3> ToStatSingle(this in int2x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int2x4> ToStatSingle(this in int2x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int3> ToStatSingle(this in int3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int3x2> ToStatSingle(this in int3x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int3x3> ToStatSingle(this in int3x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int3x4> ToStatSingle(this in int3x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int4> ToStatSingle(this in int4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int4x2> ToStatSingle(this in int4x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int4x3> ToStatSingle(this in int4x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int4x4> ToStatSingle(this in int4x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<long> ToStatSingle(this long value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<sbyte> ToStatSingle(this sbyte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<short> ToStatSingle(this short value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint> ToStatSingle(this uint value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint2> ToStatSingle(this uint2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint2x2> ToStatSingle(this in uint2x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint2x3> ToStatSingle(this in uint2x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint2x4> ToStatSingle(this in uint2x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint3> ToStatSingle(this in uint3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint3x2> ToStatSingle(this in uint3x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint3x3> ToStatSingle(this in uint3x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint3x4> ToStatSingle(this in uint3x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint4> ToStatSingle(this in uint4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint4x2> ToStatSingle(this in uint4x2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint4x3> ToStatSingle(this in uint4x3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint4x4> ToStatSingle(this in uint4x4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<ulong> ToStatSingle(this ulong value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<ushort> ToStatSingle(this ushort value)
            => new(value);

    }

}

