using System;
using Unity.Mathematics;

namespace EncosyTower.Entities.Stats
{
    [Serializable]
    public partial struct StatVariant
    {
        public static StatVariant operator +(in StatVariant rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(rhs.Type);

            return rhs.Type switch {
                StatVariantType.Byte      => new((byte)+rhs.Byte),
                StatVariantType.Double    => new((double)+rhs.Double),
                StatVariantType.Double2   => new(+rhs.Double2),
                StatVariantType.Double2x2 => new(+rhs.Double2x2),
                StatVariantType.Double2x3 => new(+rhs.Double2x3),
                StatVariantType.Double2x4 => new(+rhs.Double2x4),
                StatVariantType.Double3   => new(+rhs.Double3),
                StatVariantType.Double3x2 => new(+rhs.Double3x2),
                StatVariantType.Double3x3 => new(+rhs.Double3x3),
                StatVariantType.Double3x4 => new(+rhs.Double3x4),
                StatVariantType.Double4   => new(+rhs.Double4),
                StatVariantType.Double4x2 => new(+rhs.Double4x2),
                StatVariantType.Double4x3 => new(+rhs.Double4x3),
                StatVariantType.Double4x4 => new(+rhs.Double4x4),
                StatVariantType.Float     => new((float)+rhs.Float),
                StatVariantType.Float2    => new(+rhs.Float2),
                StatVariantType.Float2x2  => new(+rhs.Float2x2),
                StatVariantType.Float2x3  => new(+rhs.Float2x3),
                StatVariantType.Float2x4  => new(+rhs.Float2x4),
                StatVariantType.Float3    => new(+rhs.Float3),
                StatVariantType.Float3x2  => new(+rhs.Float3x2),
                StatVariantType.Float3x3  => new(+rhs.Float3x3),
                StatVariantType.Float3x4  => new(+rhs.Float3x4),
                StatVariantType.Float4    => new(+rhs.Float4),
                StatVariantType.Float4x2  => new(+rhs.Float4x2),
                StatVariantType.Float4x3  => new(+rhs.Float4x3),
                StatVariantType.Float4x4  => new(+rhs.Float4x4),
                StatVariantType.Half      => new(math.half(+(float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2(+(float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3(+(float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4(+(float4)rhs.Half4)),
                StatVariantType.Int       => new((int)+rhs.Int),
                StatVariantType.Int2      => new(+rhs.Int2),
                StatVariantType.Int2x2    => new(+rhs.Int2x2),
                StatVariantType.Int2x3    => new(+rhs.Int2x3),
                StatVariantType.Int2x4    => new(+rhs.Int2x4),
                StatVariantType.Int3      => new(+rhs.Int3),
                StatVariantType.Int3x2    => new(+rhs.Int3x2),
                StatVariantType.Int3x3    => new(+rhs.Int3x3),
                StatVariantType.Int3x4    => new(+rhs.Int3x4),
                StatVariantType.Int4      => new(+rhs.Int4),
                StatVariantType.Int4x2    => new(+rhs.Int4x2),
                StatVariantType.Int4x3    => new(+rhs.Int4x3),
                StatVariantType.Int4x4    => new(+rhs.Int4x4),
                StatVariantType.Long      => new((long)+rhs.Long),
                StatVariantType.SByte     => new((sbyte)+rhs.SByte),
                StatVariantType.Short     => new((short)+rhs.Short),
                StatVariantType.UInt      => new((uint)+rhs.UInt),
                StatVariantType.UInt2     => new(+rhs.UInt2),
                StatVariantType.UInt2x2   => new(+rhs.UInt2x2),
                StatVariantType.UInt2x3   => new(+rhs.UInt2x3),
                StatVariantType.UInt2x4   => new(+rhs.UInt2x4),
                StatVariantType.UInt3     => new(+rhs.UInt3),
                StatVariantType.UInt3x2   => new(+rhs.UInt3x2),
                StatVariantType.UInt3x3   => new(+rhs.UInt3x3),
                StatVariantType.UInt3x4   => new(+rhs.UInt3x4),
                StatVariantType.UInt4     => new(+rhs.UInt4),
                StatVariantType.UInt4x2   => new(+rhs.UInt4x2),
                StatVariantType.UInt4x3   => new(+rhs.UInt4x3),
                StatVariantType.UInt4x4   => new(+rhs.UInt4x4),
                StatVariantType.ULong     => new((ulong)+rhs.ULong),
                StatVariantType.UShort    => new((ushort)+rhs.UShort),
                _                         => throw ThrowHelper.UnaryOperatorException("+", rhs.Type),
            };
        }

        public static StatVariant operator -(in StatVariant rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(rhs.Type);

            return rhs.Type switch {
                StatVariantType.Double    => new((double)-rhs.Double),
                StatVariantType.Double2   => new(-rhs.Double2),
                StatVariantType.Double2x2 => new(-rhs.Double2x2),
                StatVariantType.Double2x3 => new(-rhs.Double2x3),
                StatVariantType.Double2x4 => new(-rhs.Double2x4),
                StatVariantType.Double3   => new(-rhs.Double3),
                StatVariantType.Double3x2 => new(-rhs.Double3x2),
                StatVariantType.Double3x3 => new(-rhs.Double3x3),
                StatVariantType.Double3x4 => new(-rhs.Double3x4),
                StatVariantType.Double4   => new(-rhs.Double4),
                StatVariantType.Double4x2 => new(-rhs.Double4x2),
                StatVariantType.Double4x3 => new(-rhs.Double4x3),
                StatVariantType.Double4x4 => new(-rhs.Double4x4),
                StatVariantType.Float     => new((float)-rhs.Float),
                StatVariantType.Float2    => new(-rhs.Float2),
                StatVariantType.Float2x2  => new(-rhs.Float2x2),
                StatVariantType.Float2x3  => new(-rhs.Float2x3),
                StatVariantType.Float2x4  => new(-rhs.Float2x4),
                StatVariantType.Float3    => new(-rhs.Float3),
                StatVariantType.Float3x2  => new(-rhs.Float3x2),
                StatVariantType.Float3x3  => new(-rhs.Float3x3),
                StatVariantType.Float3x4  => new(-rhs.Float3x4),
                StatVariantType.Float4    => new(-rhs.Float4),
                StatVariantType.Float4x2  => new(-rhs.Float4x2),
                StatVariantType.Float4x3  => new(-rhs.Float4x3),
                StatVariantType.Float4x4  => new(-rhs.Float4x4),
                StatVariantType.Half      => new(math.half(-(float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2(-(float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3(-(float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4(-(float4)rhs.Half4)),
                StatVariantType.Int       => new((int)-rhs.Int),
                StatVariantType.Int2      => new(-rhs.Int2),
                StatVariantType.Int2x2    => new(-rhs.Int2x2),
                StatVariantType.Int2x3    => new(-rhs.Int2x3),
                StatVariantType.Int2x4    => new(-rhs.Int2x4),
                StatVariantType.Int3      => new(-rhs.Int3),
                StatVariantType.Int3x2    => new(-rhs.Int3x2),
                StatVariantType.Int3x3    => new(-rhs.Int3x3),
                StatVariantType.Int3x4    => new(-rhs.Int3x4),
                StatVariantType.Int4      => new(-rhs.Int4),
                StatVariantType.Int4x2    => new(-rhs.Int4x2),
                StatVariantType.Int4x3    => new(-rhs.Int4x3),
                StatVariantType.Int4x4    => new(-rhs.Int4x4),
                StatVariantType.Long      => new((long)-rhs.Long),
                StatVariantType.SByte     => new((sbyte)-rhs.SByte),
                StatVariantType.Short     => new((short)-rhs.Short),
                _                         => throw ThrowHelper.UnaryOperatorException("-", rhs.Type),
            };
        }

        public static StatVariant operator +(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte      => new((byte)(lhs.Byte + rhs.Byte)),
                StatVariantType.Double    => new((double)(lhs.Double + rhs.Double)),
                StatVariantType.Double2   => new((lhs.Double2 + rhs.Double2)),
                StatVariantType.Double2x2 => new((lhs.Double2x2 + rhs.Double2x2)),
                StatVariantType.Double2x3 => new((lhs.Double2x3 + rhs.Double2x3)),
                StatVariantType.Double2x4 => new((lhs.Double2x4 + rhs.Double2x4)),
                StatVariantType.Double3   => new((lhs.Double3 + rhs.Double3)),
                StatVariantType.Double3x2 => new((lhs.Double3x2 + rhs.Double3x2)),
                StatVariantType.Double3x3 => new((lhs.Double3x3 + rhs.Double3x3)),
                StatVariantType.Double3x4 => new((lhs.Double3x4 + rhs.Double3x4)),
                StatVariantType.Double4   => new((lhs.Double4 + rhs.Double4)),
                StatVariantType.Double4x2 => new((lhs.Double4x2 + rhs.Double4x2)),
                StatVariantType.Double4x3 => new((lhs.Double4x3 + rhs.Double4x3)),
                StatVariantType.Double4x4 => new((lhs.Double4x4 + rhs.Double4x4)),
                StatVariantType.Float     => new((float)(lhs.Float + rhs.Float)),
                StatVariantType.Float2    => new((lhs.Float2 + rhs.Float2)),
                StatVariantType.Float2x2  => new((lhs.Float2x2 + rhs.Float2x2)),
                StatVariantType.Float2x3  => new((lhs.Float2x3 + rhs.Float2x3)),
                StatVariantType.Float2x4  => new((lhs.Float2x4 + rhs.Float2x4)),
                StatVariantType.Float3    => new((lhs.Float3 + rhs.Float3)),
                StatVariantType.Float3x2  => new((lhs.Float3x2 + rhs.Float3x2)),
                StatVariantType.Float3x3  => new((lhs.Float3x3 + rhs.Float3x3)),
                StatVariantType.Float3x4  => new((lhs.Float3x4 + rhs.Float3x4)),
                StatVariantType.Float4    => new((lhs.Float4 + rhs.Float4)),
                StatVariantType.Float4x2  => new((lhs.Float4x2 + rhs.Float4x2)),
                StatVariantType.Float4x3  => new((lhs.Float4x3 + rhs.Float4x3)),
                StatVariantType.Float4x4  => new((lhs.Float4x4 + rhs.Float4x4)),
                StatVariantType.Half      => new(math.half((float)lhs.Half + (float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2((float2)lhs.Half2 + (float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3((float3)lhs.Half3 + (float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4((float4)lhs.Half4 + (float4)rhs.Half4)),
                StatVariantType.Int       => new((int)(lhs.Int + rhs.Int)),
                StatVariantType.Int2      => new((lhs.Int2 + rhs.Int2)),
                StatVariantType.Int2x2    => new((lhs.Int2x2 + rhs.Int2x2)),
                StatVariantType.Int2x3    => new((lhs.Int2x3 + rhs.Int2x3)),
                StatVariantType.Int2x4    => new((lhs.Int2x4 + rhs.Int2x4)),
                StatVariantType.Int3      => new((lhs.Int3 + rhs.Int3)),
                StatVariantType.Int3x2    => new((lhs.Int3x2 + rhs.Int3x2)),
                StatVariantType.Int3x3    => new((lhs.Int3x3 + rhs.Int3x3)),
                StatVariantType.Int3x4    => new((lhs.Int3x4 + rhs.Int3x4)),
                StatVariantType.Int4      => new((lhs.Int4 + rhs.Int4)),
                StatVariantType.Int4x2    => new((lhs.Int4x2 + rhs.Int4x2)),
                StatVariantType.Int4x3    => new((lhs.Int4x3 + rhs.Int4x3)),
                StatVariantType.Int4x4    => new((lhs.Int4x4 + rhs.Int4x4)),
                StatVariantType.Long      => new((long)(lhs.Long + rhs.Long)),
                StatVariantType.SByte     => new((sbyte)(lhs.SByte + rhs.SByte)),
                StatVariantType.Short     => new((short)(lhs.Short + rhs.Short)),
                StatVariantType.UInt      => new((uint)(lhs.UInt + rhs.UInt)),
                StatVariantType.UInt2     => new((lhs.UInt2 + rhs.UInt2)),
                StatVariantType.UInt2x2   => new((lhs.UInt2x2 + rhs.UInt2x2)),
                StatVariantType.UInt2x3   => new((lhs.UInt2x3 + rhs.UInt2x3)),
                StatVariantType.UInt2x4   => new((lhs.UInt2x4 + rhs.UInt2x4)),
                StatVariantType.UInt3     => new((lhs.UInt3 + rhs.UInt3)),
                StatVariantType.UInt3x2   => new((lhs.UInt3x2 + rhs.UInt3x2)),
                StatVariantType.UInt3x3   => new((lhs.UInt3x3 + rhs.UInt3x3)),
                StatVariantType.UInt3x4   => new((lhs.UInt3x4 + rhs.UInt3x4)),
                StatVariantType.UInt4     => new((lhs.UInt4 + rhs.UInt4)),
                StatVariantType.UInt4x2   => new((lhs.UInt4x2 + rhs.UInt4x2)),
                StatVariantType.UInt4x3   => new((lhs.UInt4x3 + rhs.UInt4x3)),
                StatVariantType.UInt4x4   => new((lhs.UInt4x4 + rhs.UInt4x4)),
                StatVariantType.ULong     => new((ulong)(lhs.ULong + rhs.ULong)),
                StatVariantType.UShort    => new((ushort)(lhs.UShort + rhs.UShort)),
                _                         => throw ThrowHelper.OperatorException("+", lhs.Type),
            };
        }

        public static StatVariant operator -(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte      => new((byte)(lhs.Byte - rhs.Byte)),
                StatVariantType.Double    => new((double)(lhs.Double - rhs.Double)),
                StatVariantType.Double2   => new((lhs.Double2 - rhs.Double2)),
                StatVariantType.Double2x2 => new((lhs.Double2x2 - rhs.Double2x2)),
                StatVariantType.Double2x3 => new((lhs.Double2x3 - rhs.Double2x3)),
                StatVariantType.Double2x4 => new((lhs.Double2x4 - rhs.Double2x4)),
                StatVariantType.Double3   => new((lhs.Double3 - rhs.Double3)),
                StatVariantType.Double3x2 => new((lhs.Double3x2 - rhs.Double3x2)),
                StatVariantType.Double3x3 => new((lhs.Double3x3 - rhs.Double3x3)),
                StatVariantType.Double3x4 => new((lhs.Double3x4 - rhs.Double3x4)),
                StatVariantType.Double4   => new((lhs.Double4 - rhs.Double4)),
                StatVariantType.Double4x2 => new((lhs.Double4x2 - rhs.Double4x2)),
                StatVariantType.Double4x3 => new((lhs.Double4x3 - rhs.Double4x3)),
                StatVariantType.Double4x4 => new((lhs.Double4x4 - rhs.Double4x4)),
                StatVariantType.Float     => new((float)(lhs.Float - rhs.Float)),
                StatVariantType.Float2    => new((lhs.Float2 - rhs.Float2)),
                StatVariantType.Float2x2  => new((lhs.Float2x2 - rhs.Float2x2)),
                StatVariantType.Float2x3  => new((lhs.Float2x3 - rhs.Float2x3)),
                StatVariantType.Float2x4  => new((lhs.Float2x4 - rhs.Float2x4)),
                StatVariantType.Float3    => new((lhs.Float3 - rhs.Float3)),
                StatVariantType.Float3x2  => new((lhs.Float3x2 - rhs.Float3x2)),
                StatVariantType.Float3x3  => new((lhs.Float3x3 - rhs.Float3x3)),
                StatVariantType.Float3x4  => new((lhs.Float3x4 - rhs.Float3x4)),
                StatVariantType.Float4    => new((lhs.Float4 - rhs.Float4)),
                StatVariantType.Float4x2  => new((lhs.Float4x2 - rhs.Float4x2)),
                StatVariantType.Float4x3  => new((lhs.Float4x3 - rhs.Float4x3)),
                StatVariantType.Float4x4  => new((lhs.Float4x4 - rhs.Float4x4)),
                StatVariantType.Half      => new(math.half((float)lhs.Half - (float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2((float2)lhs.Half2 - (float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3((float3)lhs.Half3 - (float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4((float4)lhs.Half4 - (float4)rhs.Half4)),
                StatVariantType.Int       => new((int)(lhs.Int - rhs.Int)),
                StatVariantType.Int2      => new((lhs.Int2 - rhs.Int2)),
                StatVariantType.Int2x2    => new((lhs.Int2x2 - rhs.Int2x2)),
                StatVariantType.Int2x3    => new((lhs.Int2x3 - rhs.Int2x3)),
                StatVariantType.Int2x4    => new((lhs.Int2x4 - rhs.Int2x4)),
                StatVariantType.Int3      => new((lhs.Int3 - rhs.Int3)),
                StatVariantType.Int3x2    => new((lhs.Int3x2 - rhs.Int3x2)),
                StatVariantType.Int3x3    => new((lhs.Int3x3 - rhs.Int3x3)),
                StatVariantType.Int3x4    => new((lhs.Int3x4 - rhs.Int3x4)),
                StatVariantType.Int4      => new((lhs.Int4 - rhs.Int4)),
                StatVariantType.Int4x2    => new((lhs.Int4x2 - rhs.Int4x2)),
                StatVariantType.Int4x3    => new((lhs.Int4x3 - rhs.Int4x3)),
                StatVariantType.Int4x4    => new((lhs.Int4x4 - rhs.Int4x4)),
                StatVariantType.Long      => new((long)(lhs.Long - rhs.Long)),
                StatVariantType.SByte     => new((sbyte)(lhs.SByte - rhs.SByte)),
                StatVariantType.Short     => new((short)(lhs.Short - rhs.Short)),
                StatVariantType.UInt      => new((uint)(lhs.UInt - rhs.UInt)),
                StatVariantType.UInt2     => new((lhs.UInt2 - rhs.UInt2)),
                StatVariantType.UInt2x2   => new((lhs.UInt2x2 - rhs.UInt2x2)),
                StatVariantType.UInt2x3   => new((lhs.UInt2x3 - rhs.UInt2x3)),
                StatVariantType.UInt2x4   => new((lhs.UInt2x4 - rhs.UInt2x4)),
                StatVariantType.UInt3     => new((lhs.UInt3 - rhs.UInt3)),
                StatVariantType.UInt3x2   => new((lhs.UInt3x2 - rhs.UInt3x2)),
                StatVariantType.UInt3x3   => new((lhs.UInt3x3 - rhs.UInt3x3)),
                StatVariantType.UInt3x4   => new((lhs.UInt3x4 - rhs.UInt3x4)),
                StatVariantType.UInt4     => new((lhs.UInt4 - rhs.UInt4)),
                StatVariantType.UInt4x2   => new((lhs.UInt4x2 - rhs.UInt4x2)),
                StatVariantType.UInt4x3   => new((lhs.UInt4x3 - rhs.UInt4x3)),
                StatVariantType.UInt4x4   => new((lhs.UInt4x4 - rhs.UInt4x4)),
                StatVariantType.ULong     => new((ulong)(lhs.ULong - rhs.ULong)),
                StatVariantType.UShort    => new((ushort)(lhs.UShort - rhs.UShort)),
                _                         => throw ThrowHelper.OperatorException("-", lhs.Type),
            };
        }

        public static StatVariant operator *(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte      => new((byte)(lhs.Byte * rhs.Byte)),
                StatVariantType.Double    => new((double)(lhs.Double * rhs.Double)),
                StatVariantType.Double2   => new((lhs.Double2 * rhs.Double2)),
                StatVariantType.Double2x2 => new((lhs.Double2x2 * rhs.Double2x2)),
                StatVariantType.Double2x3 => new((lhs.Double2x3 * rhs.Double2x3)),
                StatVariantType.Double2x4 => new((lhs.Double2x4 * rhs.Double2x4)),
                StatVariantType.Double3   => new((lhs.Double3 * rhs.Double3)),
                StatVariantType.Double3x2 => new((lhs.Double3x2 * rhs.Double3x2)),
                StatVariantType.Double3x3 => new((lhs.Double3x3 * rhs.Double3x3)),
                StatVariantType.Double3x4 => new((lhs.Double3x4 * rhs.Double3x4)),
                StatVariantType.Double4   => new((lhs.Double4 * rhs.Double4)),
                StatVariantType.Double4x2 => new((lhs.Double4x2 * rhs.Double4x2)),
                StatVariantType.Double4x3 => new((lhs.Double4x3 * rhs.Double4x3)),
                StatVariantType.Double4x4 => new((lhs.Double4x4 * rhs.Double4x4)),
                StatVariantType.Float     => new((float)(lhs.Float * rhs.Float)),
                StatVariantType.Float2    => new((lhs.Float2 * rhs.Float2)),
                StatVariantType.Float2x2  => new((lhs.Float2x2 * rhs.Float2x2)),
                StatVariantType.Float2x3  => new((lhs.Float2x3 * rhs.Float2x3)),
                StatVariantType.Float2x4  => new((lhs.Float2x4 * rhs.Float2x4)),
                StatVariantType.Float3    => new((lhs.Float3 * rhs.Float3)),
                StatVariantType.Float3x2  => new((lhs.Float3x2 * rhs.Float3x2)),
                StatVariantType.Float3x3  => new((lhs.Float3x3 * rhs.Float3x3)),
                StatVariantType.Float3x4  => new((lhs.Float3x4 * rhs.Float3x4)),
                StatVariantType.Float4    => new((lhs.Float4 * rhs.Float4)),
                StatVariantType.Float4x2  => new((lhs.Float4x2 * rhs.Float4x2)),
                StatVariantType.Float4x3  => new((lhs.Float4x3 * rhs.Float4x3)),
                StatVariantType.Float4x4  => new((lhs.Float4x4 * rhs.Float4x4)),
                StatVariantType.Half      => new(math.half((float)lhs.Half * (float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2((float2)lhs.Half2 * (float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3((float3)lhs.Half3 * (float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4((float4)lhs.Half4 * (float4)rhs.Half4)),
                StatVariantType.Int       => new((int)(lhs.Int * rhs.Int)),
                StatVariantType.Int2      => new((lhs.Int2 * rhs.Int2)),
                StatVariantType.Int2x2    => new((lhs.Int2x2 * rhs.Int2x2)),
                StatVariantType.Int2x3    => new((lhs.Int2x3 * rhs.Int2x3)),
                StatVariantType.Int2x4    => new((lhs.Int2x4 * rhs.Int2x4)),
                StatVariantType.Int3      => new((lhs.Int3 * rhs.Int3)),
                StatVariantType.Int3x2    => new((lhs.Int3x2 * rhs.Int3x2)),
                StatVariantType.Int3x3    => new((lhs.Int3x3 * rhs.Int3x3)),
                StatVariantType.Int3x4    => new((lhs.Int3x4 * rhs.Int3x4)),
                StatVariantType.Int4      => new((lhs.Int4 * rhs.Int4)),
                StatVariantType.Int4x2    => new((lhs.Int4x2 * rhs.Int4x2)),
                StatVariantType.Int4x3    => new((lhs.Int4x3 * rhs.Int4x3)),
                StatVariantType.Int4x4    => new((lhs.Int4x4 * rhs.Int4x4)),
                StatVariantType.Long      => new((long)(lhs.Long * rhs.Long)),
                StatVariantType.SByte     => new((sbyte)(lhs.SByte * rhs.SByte)),
                StatVariantType.Short     => new((short)(lhs.Short * rhs.Short)),
                StatVariantType.UInt      => new((uint)(lhs.UInt * rhs.UInt)),
                StatVariantType.UInt2     => new((lhs.UInt2 * rhs.UInt2)),
                StatVariantType.UInt2x2   => new((lhs.UInt2x2 * rhs.UInt2x2)),
                StatVariantType.UInt2x3   => new((lhs.UInt2x3 * rhs.UInt2x3)),
                StatVariantType.UInt2x4   => new((lhs.UInt2x4 * rhs.UInt2x4)),
                StatVariantType.UInt3     => new((lhs.UInt3 * rhs.UInt3)),
                StatVariantType.UInt3x2   => new((lhs.UInt3x2 * rhs.UInt3x2)),
                StatVariantType.UInt3x3   => new((lhs.UInt3x3 * rhs.UInt3x3)),
                StatVariantType.UInt3x4   => new((lhs.UInt3x4 * rhs.UInt3x4)),
                StatVariantType.UInt4     => new((lhs.UInt4 * rhs.UInt4)),
                StatVariantType.UInt4x2   => new((lhs.UInt4x2 * rhs.UInt4x2)),
                StatVariantType.UInt4x3   => new((lhs.UInt4x3 * rhs.UInt4x3)),
                StatVariantType.UInt4x4   => new((lhs.UInt4x4 * rhs.UInt4x4)),
                StatVariantType.ULong     => new((ulong)(lhs.ULong * rhs.ULong)),
                StatVariantType.UShort    => new((ushort)(lhs.UShort * rhs.UShort)),
                _                         => throw ThrowHelper.OperatorException("*", lhs.Type),
            };
        }

        public static StatVariant operator /(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte      => new((byte)(lhs.Byte / rhs.Byte)),
                StatVariantType.Double    => new((double)(lhs.Double / rhs.Double)),
                StatVariantType.Double2   => new((lhs.Double2 / rhs.Double2)),
                StatVariantType.Double2x2 => new((lhs.Double2x2 / rhs.Double2x2)),
                StatVariantType.Double2x3 => new((lhs.Double2x3 / rhs.Double2x3)),
                StatVariantType.Double2x4 => new((lhs.Double2x4 / rhs.Double2x4)),
                StatVariantType.Double3   => new((lhs.Double3 / rhs.Double3)),
                StatVariantType.Double3x2 => new((lhs.Double3x2 / rhs.Double3x2)),
                StatVariantType.Double3x3 => new((lhs.Double3x3 / rhs.Double3x3)),
                StatVariantType.Double3x4 => new((lhs.Double3x4 / rhs.Double3x4)),
                StatVariantType.Double4   => new((lhs.Double4 / rhs.Double4)),
                StatVariantType.Double4x2 => new((lhs.Double4x2 / rhs.Double4x2)),
                StatVariantType.Double4x3 => new((lhs.Double4x3 / rhs.Double4x3)),
                StatVariantType.Double4x4 => new((lhs.Double4x4 / rhs.Double4x4)),
                StatVariantType.Float     => new((float)(lhs.Float / rhs.Float)),
                StatVariantType.Float2    => new((lhs.Float2 / rhs.Float2)),
                StatVariantType.Float2x2  => new((lhs.Float2x2 / rhs.Float2x2)),
                StatVariantType.Float2x3  => new((lhs.Float2x3 / rhs.Float2x3)),
                StatVariantType.Float2x4  => new((lhs.Float2x4 / rhs.Float2x4)),
                StatVariantType.Float3    => new((lhs.Float3 / rhs.Float3)),
                StatVariantType.Float3x2  => new((lhs.Float3x2 / rhs.Float3x2)),
                StatVariantType.Float3x3  => new((lhs.Float3x3 / rhs.Float3x3)),
                StatVariantType.Float3x4  => new((lhs.Float3x4 / rhs.Float3x4)),
                StatVariantType.Float4    => new((lhs.Float4 / rhs.Float4)),
                StatVariantType.Float4x2  => new((lhs.Float4x2 / rhs.Float4x2)),
                StatVariantType.Float4x3  => new((lhs.Float4x3 / rhs.Float4x3)),
                StatVariantType.Float4x4  => new((lhs.Float4x4 / rhs.Float4x4)),
                StatVariantType.Half      => new(math.half((float)lhs.Half / (float)rhs.Half)),
                StatVariantType.Half2     => new(math.half2((float2)lhs.Half2 / (float2)rhs.Half2)),
                StatVariantType.Half3     => new(math.half3((float3)lhs.Half3 / (float3)rhs.Half3)),
                StatVariantType.Half4     => new(math.half4((float4)lhs.Half4 / (float4)rhs.Half4)),
                StatVariantType.Int       => new((int)(lhs.Int / rhs.Int)),
                StatVariantType.Int2      => new((lhs.Int2 / rhs.Int2)),
                StatVariantType.Int2x2    => new((lhs.Int2x2 / rhs.Int2x2)),
                StatVariantType.Int2x3    => new((lhs.Int2x3 / rhs.Int2x3)),
                StatVariantType.Int2x4    => new((lhs.Int2x4 / rhs.Int2x4)),
                StatVariantType.Int3      => new((lhs.Int3 / rhs.Int3)),
                StatVariantType.Int3x2    => new((lhs.Int3x2 / rhs.Int3x2)),
                StatVariantType.Int3x3    => new((lhs.Int3x3 / rhs.Int3x3)),
                StatVariantType.Int3x4    => new((lhs.Int3x4 / rhs.Int3x4)),
                StatVariantType.Int4      => new((lhs.Int4 / rhs.Int4)),
                StatVariantType.Int4x2    => new((lhs.Int4x2 / rhs.Int4x2)),
                StatVariantType.Int4x3    => new((lhs.Int4x3 / rhs.Int4x3)),
                StatVariantType.Int4x4    => new((lhs.Int4x4 / rhs.Int4x4)),
                StatVariantType.Long      => new((long)(lhs.Long / rhs.Long)),
                StatVariantType.SByte     => new((sbyte)(lhs.SByte / rhs.SByte)),
                StatVariantType.Short     => new((short)(lhs.Short / rhs.Short)),
                StatVariantType.UInt      => new((uint)(lhs.UInt / rhs.UInt)),
                StatVariantType.UInt2     => new((lhs.UInt2 / rhs.UInt2)),
                StatVariantType.UInt2x2   => new((lhs.UInt2x2 / rhs.UInt2x2)),
                StatVariantType.UInt2x3   => new((lhs.UInt2x3 / rhs.UInt2x3)),
                StatVariantType.UInt2x4   => new((lhs.UInt2x4 / rhs.UInt2x4)),
                StatVariantType.UInt3     => new((lhs.UInt3 / rhs.UInt3)),
                StatVariantType.UInt3x2   => new((lhs.UInt3x2 / rhs.UInt3x2)),
                StatVariantType.UInt3x3   => new((lhs.UInt3x3 / rhs.UInt3x3)),
                StatVariantType.UInt3x4   => new((lhs.UInt3x4 / rhs.UInt3x4)),
                StatVariantType.UInt4     => new((lhs.UInt4 / rhs.UInt4)),
                StatVariantType.UInt4x2   => new((lhs.UInt4x2 / rhs.UInt4x2)),
                StatVariantType.UInt4x3   => new((lhs.UInt4x3 / rhs.UInt4x3)),
                StatVariantType.UInt4x4   => new((lhs.UInt4x4 / rhs.UInt4x4)),
                StatVariantType.ULong     => new((ulong)(lhs.ULong / rhs.ULong)),
                StatVariantType.UShort    => new((ushort)(lhs.UShort / rhs.UShort)),
                _                         => throw ThrowHelper.OperatorException("/", lhs.Type),
            };
        }

        public static StatVariant operator ~(in StatVariant rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(rhs.Type);

            return rhs.Type switch {
                StatVariantType.Byte    => new((byte)~rhs.Byte),
                StatVariantType.Int     => new((int)~rhs.Int),
                StatVariantType.Int2    => new(~rhs.Int2),
                StatVariantType.Int2x2  => new(~rhs.Int2x2),
                StatVariantType.Int2x3  => new(~rhs.Int2x3),
                StatVariantType.Int2x4  => new(~rhs.Int2x4),
                StatVariantType.Int3    => new(~rhs.Int3),
                StatVariantType.Int3x2  => new(~rhs.Int3x2),
                StatVariantType.Int3x3  => new(~rhs.Int3x3),
                StatVariantType.Int3x4  => new(~rhs.Int3x4),
                StatVariantType.Int4    => new(~rhs.Int4),
                StatVariantType.Int4x2  => new(~rhs.Int4x2),
                StatVariantType.Int4x3  => new(~rhs.Int4x3),
                StatVariantType.Int4x4  => new(~rhs.Int4x4),
                StatVariantType.Long    => new((long)~rhs.Long),
                StatVariantType.SByte   => new((sbyte)~rhs.SByte),
                StatVariantType.Short   => new((short)~rhs.Short),
                StatVariantType.UInt    => new((uint)~rhs.UInt),
                StatVariantType.UInt2   => new(~rhs.UInt2),
                StatVariantType.UInt2x2 => new(~rhs.UInt2x2),
                StatVariantType.UInt2x3 => new(~rhs.UInt2x3),
                StatVariantType.UInt2x4 => new(~rhs.UInt2x4),
                StatVariantType.UInt3   => new(~rhs.UInt3),
                StatVariantType.UInt3x2 => new(~rhs.UInt3x2),
                StatVariantType.UInt3x3 => new(~rhs.UInt3x3),
                StatVariantType.UInt3x4 => new(~rhs.UInt3x4),
                StatVariantType.UInt4   => new(~rhs.UInt4),
                StatVariantType.UInt4x2 => new(~rhs.UInt4x2),
                StatVariantType.UInt4x3 => new(~rhs.UInt4x3),
                StatVariantType.UInt4x4 => new(~rhs.UInt4x4),
                StatVariantType.ULong   => new((ulong)~rhs.ULong),
                StatVariantType.UShort  => new((ushort)~rhs.UShort),
                _                       => throw ThrowHelper.UnaryOperatorException("~", rhs.Type),
            };
        }

        public static StatVariant operator !(in StatVariant rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(rhs.Type);

            return rhs.Type switch {
                StatVariantType.Bool    => new(!rhs.Bool),
                StatVariantType.Bool2   => new(!rhs.Bool2),
                StatVariantType.Bool2x2 => new(!rhs.Bool2x2),
                StatVariantType.Bool2x3 => new(!rhs.Bool2x3),
                StatVariantType.Bool2x4 => new(!rhs.Bool2x4),
                StatVariantType.Bool3   => new(!rhs.Bool3),
                StatVariantType.Bool3x2 => new(!rhs.Bool3x2),
                StatVariantType.Bool3x3 => new(!rhs.Bool3x3),
                StatVariantType.Bool3x4 => new(!rhs.Bool3x4),
                StatVariantType.Bool4   => new(!rhs.Bool4),
                StatVariantType.Bool4x2 => new(!rhs.Bool4x2),
                StatVariantType.Bool4x3 => new(!rhs.Bool4x3),
                StatVariantType.Bool4x4 => new(!rhs.Bool4x4),
                _                       => throw ThrowHelper.UnaryOperatorException("!", rhs.Type),
            };
        }

        public static StatVariant operator <<(in StatVariant lhs, int rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte    => new((byte)(lhs.Byte << rhs)),
                StatVariantType.Int     => new((int)(lhs.Int << rhs)),
                StatVariantType.Int2    => new((lhs.Int2 << rhs)),
                StatVariantType.Int2x2  => new((lhs.Int2x2 << rhs)),
                StatVariantType.Int2x3  => new((lhs.Int2x3 << rhs)),
                StatVariantType.Int2x4  => new((lhs.Int2x4 << rhs)),
                StatVariantType.Int3    => new((lhs.Int3 << rhs)),
                StatVariantType.Int3x2  => new((lhs.Int3x2 << rhs)),
                StatVariantType.Int3x3  => new((lhs.Int3x3 << rhs)),
                StatVariantType.Int3x4  => new((lhs.Int3x4 << rhs)),
                StatVariantType.Int4    => new((lhs.Int4 << rhs)),
                StatVariantType.Int4x2  => new((lhs.Int4x2 << rhs)),
                StatVariantType.Int4x3  => new((lhs.Int4x3 << rhs)),
                StatVariantType.Int4x4  => new((lhs.Int4x4 << rhs)),
                StatVariantType.Long    => new((long)(lhs.Long << rhs)),
                StatVariantType.SByte   => new((sbyte)(lhs.SByte << rhs)),
                StatVariantType.Short   => new((short)(lhs.Short << rhs)),
                StatVariantType.UInt    => new((uint)(lhs.UInt << rhs)),
                StatVariantType.UInt2   => new((lhs.UInt2 << rhs)),
                StatVariantType.UInt2x2 => new((lhs.UInt2x2 << rhs)),
                StatVariantType.UInt2x3 => new((lhs.UInt2x3 << rhs)),
                StatVariantType.UInt2x4 => new((lhs.UInt2x4 << rhs)),
                StatVariantType.UInt3   => new((lhs.UInt3 << rhs)),
                StatVariantType.UInt3x2 => new((lhs.UInt3x2 << rhs)),
                StatVariantType.UInt3x3 => new((lhs.UInt3x3 << rhs)),
                StatVariantType.UInt3x4 => new((lhs.UInt3x4 << rhs)),
                StatVariantType.UInt4   => new((lhs.UInt4 << rhs)),
                StatVariantType.UInt4x2 => new((lhs.UInt4x2 << rhs)),
                StatVariantType.UInt4x3 => new((lhs.UInt4x3 << rhs)),
                StatVariantType.UInt4x4 => new((lhs.UInt4x4 << rhs)),
                StatVariantType.ULong   => new((ulong)(lhs.ULong << rhs)),
                StatVariantType.UShort  => new((ushort)(lhs.UShort << rhs)),
                _                       => throw ThrowHelper.OperatorException("<<", lhs.Type),
            };
        }

        public static StatVariant operator >>(in StatVariant lhs, int rhs)
        {
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Byte    => new((byte)(lhs.Byte >> rhs)),
                StatVariantType.Int     => new((int)(lhs.Int >> rhs)),
                StatVariantType.Int2    => new((lhs.Int2 >> rhs)),
                StatVariantType.Int2x2  => new((lhs.Int2x2 >> rhs)),
                StatVariantType.Int2x3  => new((lhs.Int2x3 >> rhs)),
                StatVariantType.Int2x4  => new((lhs.Int2x4 >> rhs)),
                StatVariantType.Int3    => new((lhs.Int3 >> rhs)),
                StatVariantType.Int3x2  => new((lhs.Int3x2 >> rhs)),
                StatVariantType.Int3x3  => new((lhs.Int3x3 >> rhs)),
                StatVariantType.Int3x4  => new((lhs.Int3x4 >> rhs)),
                StatVariantType.Int4    => new((lhs.Int4 >> rhs)),
                StatVariantType.Int4x2  => new((lhs.Int4x2 >> rhs)),
                StatVariantType.Int4x3  => new((lhs.Int4x3 >> rhs)),
                StatVariantType.Int4x4  => new((lhs.Int4x4 >> rhs)),
                StatVariantType.Long    => new((long)(lhs.Long >> rhs)),
                StatVariantType.SByte   => new((sbyte)(lhs.SByte >> rhs)),
                StatVariantType.Short   => new((short)(lhs.Short >> rhs)),
                StatVariantType.UInt    => new((uint)(lhs.UInt >> rhs)),
                StatVariantType.UInt2   => new((lhs.UInt2 >> rhs)),
                StatVariantType.UInt2x2 => new((lhs.UInt2x2 >> rhs)),
                StatVariantType.UInt2x3 => new((lhs.UInt2x3 >> rhs)),
                StatVariantType.UInt2x4 => new((lhs.UInt2x4 >> rhs)),
                StatVariantType.UInt3   => new((lhs.UInt3 >> rhs)),
                StatVariantType.UInt3x2 => new((lhs.UInt3x2 >> rhs)),
                StatVariantType.UInt3x3 => new((lhs.UInt3x3 >> rhs)),
                StatVariantType.UInt3x4 => new((lhs.UInt3x4 >> rhs)),
                StatVariantType.UInt4   => new((lhs.UInt4 >> rhs)),
                StatVariantType.UInt4x2 => new((lhs.UInt4x2 >> rhs)),
                StatVariantType.UInt4x3 => new((lhs.UInt4x3 >> rhs)),
                StatVariantType.UInt4x4 => new((lhs.UInt4x4 >> rhs)),
                StatVariantType.ULong   => new((ulong)(lhs.ULong >> rhs)),
                StatVariantType.UShort  => new((ushort)(lhs.UShort >> rhs)),
                _                       => throw ThrowHelper.OperatorException(">>", lhs.Type),
            };
        }

        public static StatVariant operator &(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Bool      => new((lhs.Bool & rhs.Bool)),
                StatVariantType.Bool2     => new((lhs.Bool2 & rhs.Bool2)),
                StatVariantType.Bool2x2   => new((lhs.Bool2x2 & rhs.Bool2x2)),
                StatVariantType.Bool2x3   => new((lhs.Bool2x3 & rhs.Bool2x3)),
                StatVariantType.Bool2x4   => new((lhs.Bool2x4 & rhs.Bool2x4)),
                StatVariantType.Bool3     => new((lhs.Bool3 & rhs.Bool3)),
                StatVariantType.Bool3x2   => new((lhs.Bool3x2 & rhs.Bool3x2)),
                StatVariantType.Bool3x3   => new((lhs.Bool3x3 & rhs.Bool3x3)),
                StatVariantType.Bool3x4   => new((lhs.Bool3x4 & rhs.Bool3x4)),
                StatVariantType.Bool4     => new((lhs.Bool4 & rhs.Bool4)),
                StatVariantType.Bool4x2   => new((lhs.Bool4x2 & rhs.Bool4x2)),
                StatVariantType.Bool4x3   => new((lhs.Bool4x3 & rhs.Bool4x3)),
                StatVariantType.Bool4x4   => new((lhs.Bool4x4 & rhs.Bool4x4)),
                StatVariantType.Byte      => new((byte)(lhs.Byte & rhs.Byte)),
                StatVariantType.Int       => new((int)(lhs.Int & rhs.Int)),
                StatVariantType.Int2      => new((lhs.Int2 & rhs.Int2)),
                StatVariantType.Int2x2    => new((lhs.Int2x2 & rhs.Int2x2)),
                StatVariantType.Int2x3    => new((lhs.Int2x3 & rhs.Int2x3)),
                StatVariantType.Int2x4    => new((lhs.Int2x4 & rhs.Int2x4)),
                StatVariantType.Int3      => new((lhs.Int3 & rhs.Int3)),
                StatVariantType.Int3x2    => new((lhs.Int3x2 & rhs.Int3x2)),
                StatVariantType.Int3x3    => new((lhs.Int3x3 & rhs.Int3x3)),
                StatVariantType.Int3x4    => new((lhs.Int3x4 & rhs.Int3x4)),
                StatVariantType.Int4      => new((lhs.Int4 & rhs.Int4)),
                StatVariantType.Int4x2    => new((lhs.Int4x2 & rhs.Int4x2)),
                StatVariantType.Int4x3    => new((lhs.Int4x3 & rhs.Int4x3)),
                StatVariantType.Int4x4    => new((lhs.Int4x4 & rhs.Int4x4)),
                StatVariantType.Long      => new((long)(lhs.Long & rhs.Long)),
                StatVariantType.SByte     => new((sbyte)(lhs.SByte & rhs.SByte)),
                StatVariantType.Short     => new((short)(lhs.Short & rhs.Short)),
                StatVariantType.UInt      => new((uint)(lhs.UInt & rhs.UInt)),
                StatVariantType.UInt2     => new((lhs.UInt2 & rhs.UInt2)),
                StatVariantType.UInt2x2   => new((lhs.UInt2x2 & rhs.UInt2x2)),
                StatVariantType.UInt2x3   => new((lhs.UInt2x3 & rhs.UInt2x3)),
                StatVariantType.UInt2x4   => new((lhs.UInt2x4 & rhs.UInt2x4)),
                StatVariantType.UInt3     => new((lhs.UInt3 & rhs.UInt3)),
                StatVariantType.UInt3x2   => new((lhs.UInt3x2 & rhs.UInt3x2)),
                StatVariantType.UInt3x3   => new((lhs.UInt3x3 & rhs.UInt3x3)),
                StatVariantType.UInt3x4   => new((lhs.UInt3x4 & rhs.UInt3x4)),
                StatVariantType.UInt4     => new((lhs.UInt4 & rhs.UInt4)),
                StatVariantType.UInt4x2   => new((lhs.UInt4x2 & rhs.UInt4x2)),
                StatVariantType.UInt4x3   => new((lhs.UInt4x3 & rhs.UInt4x3)),
                StatVariantType.UInt4x4   => new((lhs.UInt4x4 & rhs.UInt4x4)),
                StatVariantType.ULong     => new((ulong)(lhs.ULong & rhs.ULong)),
                StatVariantType.UShort    => new((ushort)(lhs.UShort & rhs.UShort)),
                _                         => throw ThrowHelper.OperatorException("&", lhs.Type),
            };
        }

        public static StatVariant operator |(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Bool    => new((lhs.Bool | rhs.Bool)),
                StatVariantType.Bool2   => new((lhs.Bool2 | rhs.Bool2)),
                StatVariantType.Bool2x2 => new((lhs.Bool2x2 | rhs.Bool2x2)),
                StatVariantType.Bool2x3 => new((lhs.Bool2x3 | rhs.Bool2x3)),
                StatVariantType.Bool2x4 => new((lhs.Bool2x4 | rhs.Bool2x4)),
                StatVariantType.Bool3   => new((lhs.Bool3 | rhs.Bool3)),
                StatVariantType.Bool3x2 => new((lhs.Bool3x2 | rhs.Bool3x2)),
                StatVariantType.Bool3x3 => new((lhs.Bool3x3 | rhs.Bool3x3)),
                StatVariantType.Bool3x4 => new((lhs.Bool3x4 | rhs.Bool3x4)),
                StatVariantType.Bool4   => new((lhs.Bool4 | rhs.Bool4)),
                StatVariantType.Bool4x2 => new((lhs.Bool4x2 | rhs.Bool4x2)),
                StatVariantType.Bool4x3 => new((lhs.Bool4x3 | rhs.Bool4x3)),
                StatVariantType.Bool4x4 => new((lhs.Bool4x4 | rhs.Bool4x4)),
                StatVariantType.Byte    => new((byte)(lhs.Byte | rhs.Byte)),
                StatVariantType.Int     => new((int)(lhs.Int | rhs.Int)),
                StatVariantType.Int2    => new((lhs.Int2 | rhs.Int2)),
                StatVariantType.Int2x2  => new((lhs.Int2x2 | rhs.Int2x2)),
                StatVariantType.Int2x3  => new((lhs.Int2x3 | rhs.Int2x3)),
                StatVariantType.Int2x4  => new((lhs.Int2x4 | rhs.Int2x4)),
                StatVariantType.Int3    => new((lhs.Int3 | rhs.Int3)),
                StatVariantType.Int3x2  => new((lhs.Int3x2 | rhs.Int3x2)),
                StatVariantType.Int3x3  => new((lhs.Int3x3 | rhs.Int3x3)),
                StatVariantType.Int3x4  => new((lhs.Int3x4 | rhs.Int3x4)),
                StatVariantType.Int4    => new((lhs.Int4 | rhs.Int4)),
                StatVariantType.Int4x2  => new((lhs.Int4x2 | rhs.Int4x2)),
                StatVariantType.Int4x3  => new((lhs.Int4x3 | rhs.Int4x3)),
                StatVariantType.Int4x4  => new((lhs.Int4x4 | rhs.Int4x4)),
                StatVariantType.Long    => new((long)(lhs.Long | rhs.Long)),
                StatVariantType.SByte   => new((sbyte)(lhs.SByte | rhs.SByte)),
                StatVariantType.Short   => new((short)(lhs.Short | rhs.Short)),
                StatVariantType.UInt    => new((uint)(lhs.UInt | rhs.UInt)),
                StatVariantType.UInt2   => new((lhs.UInt2 | rhs.UInt2)),
                StatVariantType.UInt2x2 => new((lhs.UInt2x2 | rhs.UInt2x2)),
                StatVariantType.UInt2x3 => new((lhs.UInt2x3 | rhs.UInt2x3)),
                StatVariantType.UInt2x4 => new((lhs.UInt2x4 | rhs.UInt2x4)),
                StatVariantType.UInt3   => new((lhs.UInt3 | rhs.UInt3)),
                StatVariantType.UInt3x2 => new((lhs.UInt3x2 | rhs.UInt3x2)),
                StatVariantType.UInt3x3 => new((lhs.UInt3x3 | rhs.UInt3x3)),
                StatVariantType.UInt3x4 => new((lhs.UInt3x4 | rhs.UInt3x4)),
                StatVariantType.UInt4   => new((lhs.UInt4 | rhs.UInt4)),
                StatVariantType.UInt4x2 => new((lhs.UInt4x2 | rhs.UInt4x2)),
                StatVariantType.UInt4x3 => new((lhs.UInt4x3 | rhs.UInt4x3)),
                StatVariantType.UInt4x4 => new((lhs.UInt4x4 | rhs.UInt4x4)),
                StatVariantType.ULong   => new((ulong)(lhs.ULong | rhs.ULong)),
                StatVariantType.UShort  => new((ushort)(lhs.UShort | rhs.UShort)),
                _                       => throw ThrowHelper.OperatorException("|", lhs.Type),
            };
        }

        public static StatVariant operator ^(in StatVariant lhs, in StatVariant rhs)
        {
            ThrowHelper.ThrowIfMismatchedTypes(lhs.Type, rhs.Type);
            ThrowHelper.ThrowIfUnsupportedType(lhs.Type);

            return lhs.Type switch {
                StatVariantType.Bool    => new((lhs.Bool ^ rhs.Bool)),
                StatVariantType.Bool2   => new((lhs.Bool2 ^ rhs.Bool2)),
                StatVariantType.Bool2x2 => new((lhs.Bool2x2 ^ rhs.Bool2x2)),
                StatVariantType.Bool2x3 => new((lhs.Bool2x3 ^ rhs.Bool2x3)),
                StatVariantType.Bool2x4 => new((lhs.Bool2x4 ^ rhs.Bool2x4)),
                StatVariantType.Bool3   => new((lhs.Bool3 ^ rhs.Bool3)),
                StatVariantType.Bool3x2 => new((lhs.Bool3x2 ^ rhs.Bool3x2)),
                StatVariantType.Bool3x3 => new((lhs.Bool3x3 ^ rhs.Bool3x3)),
                StatVariantType.Bool3x4 => new((lhs.Bool3x4 ^ rhs.Bool3x4)),
                StatVariantType.Bool4   => new((lhs.Bool4 ^ rhs.Bool4)),
                StatVariantType.Bool4x2 => new((lhs.Bool4x2 ^ rhs.Bool4x2)),
                StatVariantType.Bool4x3 => new((lhs.Bool4x3 ^ rhs.Bool4x3)),
                StatVariantType.Bool4x4 => new((lhs.Bool4x4 ^ rhs.Bool4x4)),
                StatVariantType.Byte    => new((byte)(lhs.Byte ^ rhs.Byte)),
                StatVariantType.Int     => new((int)(lhs.Int ^ rhs.Int)),
                StatVariantType.Int2    => new((lhs.Int2 ^ rhs.Int2)),
                StatVariantType.Int2x2  => new((lhs.Int2x2 ^ rhs.Int2x2)),
                StatVariantType.Int2x3  => new((lhs.Int2x3 ^ rhs.Int2x3)),
                StatVariantType.Int2x4  => new((lhs.Int2x4 ^ rhs.Int2x4)),
                StatVariantType.Int3    => new((lhs.Int3 ^ rhs.Int3)),
                StatVariantType.Int3x2  => new((lhs.Int3x2 ^ rhs.Int3x2)),
                StatVariantType.Int3x3  => new((lhs.Int3x3 ^ rhs.Int3x3)),
                StatVariantType.Int3x4  => new((lhs.Int3x4 ^ rhs.Int3x4)),
                StatVariantType.Int4    => new((lhs.Int4 ^ rhs.Int4)),
                StatVariantType.Int4x2  => new((lhs.Int4x2 ^ rhs.Int4x2)),
                StatVariantType.Int4x3  => new((lhs.Int4x3 ^ rhs.Int4x3)),
                StatVariantType.Int4x4  => new((lhs.Int4x4 ^ rhs.Int4x4)),
                StatVariantType.Long    => new((long)(lhs.Long ^ rhs.Long)),
                StatVariantType.SByte   => new((sbyte)(lhs.SByte ^ rhs.SByte)),
                StatVariantType.Short   => new((short)(lhs.Short ^ rhs.Short)),
                StatVariantType.UInt    => new((uint)(lhs.UInt ^ rhs.UInt)),
                StatVariantType.UInt2   => new((lhs.UInt2 ^ rhs.UInt2)),
                StatVariantType.UInt2x2 => new((lhs.UInt2x2 ^ rhs.UInt2x2)),
                StatVariantType.UInt2x3 => new((lhs.UInt2x3 ^ rhs.UInt2x3)),
                StatVariantType.UInt2x4 => new((lhs.UInt2x4 ^ rhs.UInt2x4)),
                StatVariantType.UInt3   => new((lhs.UInt3 ^ rhs.UInt3)),
                StatVariantType.UInt3x2 => new((lhs.UInt3x2 ^ rhs.UInt3x2)),
                StatVariantType.UInt3x3 => new((lhs.UInt3x3 ^ rhs.UInt3x3)),
                StatVariantType.UInt3x4 => new((lhs.UInt3x4 ^ rhs.UInt3x4)),
                StatVariantType.UInt4   => new((lhs.UInt4 ^ rhs.UInt4)),
                StatVariantType.UInt4x2 => new((lhs.UInt4x2 ^ rhs.UInt4x2)),
                StatVariantType.UInt4x3 => new((lhs.UInt4x3 ^ rhs.UInt4x3)),
                StatVariantType.UInt4x4 => new((lhs.UInt4x4 ^ rhs.UInt4x4)),
                StatVariantType.ULong   => new((ulong)(lhs.ULong ^ rhs.ULong)),
                StatVariantType.UShort  => new((ushort)(lhs.UShort ^ rhs.UShort)),
                _                       => throw ThrowHelper.OperatorException("^", lhs.Type),
            };
        }

        public static StatVariant Min(in StatVariant a, in StatVariant b)
        {
            ThrowHelper.ThrowIfMismatchedTypes(a.Type, b.Type);
            ThrowHelper.ThrowIfUnsupportedType(a.Type);

            return a.Type switch {
                StatVariantType.Byte    => new StatVariant((byte)math.min((uint)a.Byte, (uint)b.Byte)),
                StatVariantType.Double  => new StatVariant((double)math.min(a.Double, b.Double)),
                StatVariantType.Double2 => new StatVariant(math.min(a.Double2, b.Double2)),
                StatVariantType.Double3 => new StatVariant(math.min(a.Double3, b.Double3)),
                StatVariantType.Double4 => new StatVariant(math.min(a.Double4, b.Double4)),
                StatVariantType.Float   => new StatVariant((float)math.min(a.Float, b.Float)),
                StatVariantType.Float2  => new StatVariant(math.min(a.Float2, b.Float2)),
                StatVariantType.Float3  => new StatVariant(math.min(a.Float3, b.Float3)),
                StatVariantType.Float4  => new StatVariant(math.min(a.Float4, b.Float4)),
                StatVariantType.Half    => new StatVariant(math.half(math.min(a.Half, b.Half))),
                StatVariantType.Half2   => new StatVariant(math.half2(math.min(a.Half2, b.Half2))),
                StatVariantType.Half3   => new StatVariant(math.half3(math.min(a.Half3, b.Half3))),
                StatVariantType.Half4   => new StatVariant(math.half4(math.min(a.Half4, b.Half4))),
                StatVariantType.Int     => new StatVariant((int)math.min(a.Int, b.Int)),
                StatVariantType.Int2    => new StatVariant(math.min(a.Int2, b.Int2)),
                StatVariantType.Int3    => new StatVariant(math.min(a.Int3, b.Int3)),
                StatVariantType.Int4    => new StatVariant(math.min(a.Int4, b.Int4)),
                StatVariantType.Long    => new StatVariant((long)math.min(a.Long, b.Long)),
                StatVariantType.SByte   => new StatVariant((sbyte)math.min(a.SByte, b.SByte)),
                StatVariantType.Short   => new StatVariant((short)math.min(a.Short, b.Short)),
                StatVariantType.UInt    => new StatVariant((uint)math.min(a.UInt, b.UInt)),
                StatVariantType.UInt2   => new StatVariant(math.min(a.UInt2, b.UInt2)),
                StatVariantType.UInt3   => new StatVariant(math.min(a.UInt3, b.UInt3)),
                StatVariantType.UInt4   => new StatVariant(math.min(a.UInt4, b.UInt4)),
                StatVariantType.ULong   => new StatVariant((ulong)math.min(a.ULong, b.ULong)),
                StatVariantType.UShort  => new StatVariant((ushort)math.min((uint)a.UShort, (uint)b.UShort)),
                _                       => throw ThrowHelper.FuncException("Max", a.Type),
            };
        }

        public static StatVariant Max(in StatVariant a, in StatVariant b)
        {
            ThrowHelper.ThrowIfMismatchedTypes(a.Type, b.Type);
            ThrowHelper.ThrowIfUnsupportedType(a.Type);

            return a.Type switch {
                StatVariantType.Byte    => new StatVariant((byte)math.max((uint)a.Byte, (uint)b.Byte)),
                StatVariantType.Double  => new StatVariant((double)math.max(a.Double, b.Double)),
                StatVariantType.Double2 => new StatVariant(math.max(a.Double2, b.Double2)),
                StatVariantType.Double3 => new StatVariant(math.max(a.Double3, b.Double3)),
                StatVariantType.Double4 => new StatVariant(math.max(a.Double4, b.Double4)),
                StatVariantType.Float   => new StatVariant((float)math.max(a.Float, b.Float)),
                StatVariantType.Float2  => new StatVariant(math.max(a.Float2, b.Float2)),
                StatVariantType.Float3  => new StatVariant(math.max(a.Float3, b.Float3)),
                StatVariantType.Float4  => new StatVariant(math.max(a.Float4, b.Float4)),
                StatVariantType.Half    => new StatVariant(math.half(math.max(a.Half, b.Half))),
                StatVariantType.Half2   => new StatVariant(math.half2(math.max(a.Half2, b.Half2))),
                StatVariantType.Half3   => new StatVariant(math.half3(math.max(a.Half3, b.Half3))),
                StatVariantType.Half4   => new StatVariant(math.half4(math.max(a.Half4, b.Half4))),
                StatVariantType.Int     => new StatVariant((int)math.max(a.Int, b.Int)),
                StatVariantType.Int2    => new StatVariant(math.max(a.Int2, b.Int2)),
                StatVariantType.Int3    => new StatVariant(math.max(a.Int3, b.Int3)),
                StatVariantType.Int4    => new StatVariant(math.max(a.Int4, b.Int4)),
                StatVariantType.Long    => new StatVariant((long)math.max(a.Long, b.Long)),
                StatVariantType.SByte   => new StatVariant((sbyte)math.max(a.SByte, b.SByte)),
                StatVariantType.Short   => new StatVariant((short)math.max(a.Short, b.Short)),
                StatVariantType.UInt    => new StatVariant((uint)math.max(a.UInt, b.UInt)),
                StatVariantType.UInt2   => new StatVariant(math.max(a.UInt2, b.UInt2)),
                StatVariantType.UInt3   => new StatVariant(math.max(a.UInt3, b.UInt3)),
                StatVariantType.UInt4   => new StatVariant(math.max(a.UInt4, b.UInt4)),
                StatVariantType.ULong   => new StatVariant((ulong)math.max(a.ULong, b.ULong)),
                StatVariantType.UShort  => new StatVariant((ushort)math.max((uint)a.UShort, (uint)b.UShort)),
                _                       => throw ThrowHelper.FuncException("Max", a.Type),
            };
        }

        public static StatVariant Clamp(
              in StatVariant valueToClamp
            , in StatVariant lowerBound
            , in StatVariant upperBound
        )
        {
            ThrowHelper.ThrowIfMismatchedTypes(lowerBound.Type, upperBound.Type);
            ThrowHelper.ThrowIfMismatchedTypes(valueToClamp.Type, lowerBound.Type);
            ThrowHelper.ThrowIfUnsupportedType(valueToClamp.Type);

            return valueToClamp.Type switch {
                StatVariantType.Byte    => new StatVariant((byte)math.clamp((uint)valueToClamp.Byte, (uint)lowerBound.Byte, (uint)upperBound.Byte)),
                StatVariantType.Double  => new StatVariant((double)math.clamp(valueToClamp.Double, lowerBound.Double, upperBound.Double)),
                StatVariantType.Double2 => new StatVariant(math.clamp(valueToClamp.Double2, lowerBound.Double2, upperBound.Double2)),
                StatVariantType.Double3 => new StatVariant(math.clamp(valueToClamp.Double3, lowerBound.Double3, upperBound.Double3)),
                StatVariantType.Double4 => new StatVariant(math.clamp(valueToClamp.Double4, lowerBound.Double4, upperBound.Double4)),
                StatVariantType.Float   => new StatVariant((float)math.clamp(valueToClamp.Float, lowerBound.Float, upperBound.Float)),
                StatVariantType.Float2  => new StatVariant(math.clamp(valueToClamp.Float2, lowerBound.Float2, upperBound.Float2)),
                StatVariantType.Float3  => new StatVariant(math.clamp(valueToClamp.Float3, lowerBound.Float3, upperBound.Float3)),
                StatVariantType.Float4  => new StatVariant(math.clamp(valueToClamp.Float4, lowerBound.Float4, upperBound.Float4)),
                StatVariantType.Half    => new StatVariant(math.half(math.clamp(valueToClamp.Half, lowerBound.Half, upperBound.Half))),
                StatVariantType.Half2   => new StatVariant(math.half2(math.clamp(valueToClamp.Half2, lowerBound.Half2, upperBound.Half2))),
                StatVariantType.Half3   => new StatVariant(math.half3(math.clamp(valueToClamp.Half3, lowerBound.Half3, upperBound.Half3))),
                StatVariantType.Half4   => new StatVariant(math.half4(math.clamp(valueToClamp.Half4, lowerBound.Half4, upperBound.Half4))),
                StatVariantType.Int     => new StatVariant((int)math.clamp(valueToClamp.Int, lowerBound.Int, upperBound.Int)),
                StatVariantType.Int2    => new StatVariant(math.clamp(valueToClamp.Int2, lowerBound.Int2, upperBound.Int2)),
                StatVariantType.Int3    => new StatVariant(math.clamp(valueToClamp.Int3, lowerBound.Int3, upperBound.Int3)),
                StatVariantType.Int4    => new StatVariant(math.clamp(valueToClamp.Int4, lowerBound.Int4, upperBound.Int4)),
                StatVariantType.Long    => new StatVariant((long)math.clamp(valueToClamp.Long, lowerBound.Long, upperBound.Long)),
                StatVariantType.SByte   => new StatVariant((sbyte)math.clamp(valueToClamp.SByte, lowerBound.SByte, upperBound.SByte)),
                StatVariantType.Short   => new StatVariant((short)math.clamp(valueToClamp.Short, lowerBound.Short, upperBound.Short)),
                StatVariantType.UInt    => new StatVariant((uint)math.clamp(valueToClamp.UInt, lowerBound.UInt, upperBound.UInt)),
                StatVariantType.UInt2   => new StatVariant(math.clamp(valueToClamp.UInt2, lowerBound.UInt2, upperBound.UInt2)),
                StatVariantType.UInt3   => new StatVariant(math.clamp(valueToClamp.UInt3, lowerBound.UInt3, upperBound.UInt3)),
                StatVariantType.UInt4   => new StatVariant(math.clamp(valueToClamp.UInt4, lowerBound.UInt4, upperBound.UInt4)),
                StatVariantType.ULong   => new StatVariant((ulong)math.clamp(valueToClamp.ULong, lowerBound.ULong, upperBound.ULong)),
                StatVariantType.UShort  => new StatVariant((ushort)math.clamp((uint)valueToClamp.UShort, (uint)lowerBound.UShort, (uint)upperBound.UShort)),
                _                       => throw ThrowHelper.FuncException("Clamp", valueToClamp.Type),
            };
        }
    }
}
