/// <auto-generated>
///******************************************************///
///                                                      ///
/// This file is auto-generated by StatDataSizeGenerator ///
///              DO NOT manually modify it!              ///
///                                                      ///
///******************************************************///
/// </auto-generated>

/// <reference>
/// LIST OF SUPPORTED TYPES AND THEIR SIZE
/// TYPE      | SIZE (bytes)
/// --------- | ------------
/// Bool      | 1
/// Bool2     | 2
/// Bool2x2   | 4
/// Bool2x3   | 6
/// Bool2x4   | 8
/// Bool3     | 3
/// Bool3x2   | 6
/// Bool3x3   | 9
/// Bool3x4   | 12
/// Bool4     | 4
/// Bool4x2   | 8
/// Bool4x3   | 12
/// Bool4x4   | 16
/// Byte      | 1
/// Double    | 8
/// Double2   | 16
/// Double2x2 | 32
/// Double2x3 | 48
/// Double2x4 | 64
/// Double3   | 24
/// Double3x2 | 48
/// Double3x3 | 72
/// Double3x4 | 96
/// Double4   | 32
/// Double4x2 | 64
/// Double4x3 | 96
/// Double4x4 | 128
/// Float     | 4
/// Float2    | 8
/// Float2x2  | 16
/// Float2x3  | 24
/// Float2x4  | 32
/// Float3    | 12
/// Float3x2  | 24
/// Float3x3  | 36
/// Float3x4  | 48
/// Float4    | 16
/// Float4x2  | 32
/// Float4x3  | 48
/// Float4x4  | 64
/// Half      | 2
/// Half2     | 4
/// Half3     | 6
/// Half4     | 8
/// Int       | 4
/// Int2      | 8
/// Int2x2    | 16
/// Int2x3    | 24
/// Int2x4    | 32
/// Int3      | 12
/// Int3x2    | 24
/// Int3x3    | 36
/// Int3x4    | 48
/// Int4      | 16
/// Int4x2    | 32
/// Int4x3    | 48
/// Int4x4    | 64
/// Long      | 8
/// SByte     | 1
/// Short     | 2
/// UInt      | 4
/// UInt2     | 8
/// UInt2x2   | 16
/// UInt2x3   | 24
/// UInt2x4   | 32
/// UInt3     | 12
/// UInt3x2   | 24
/// UInt3x3   | 36
/// UInt3x4   | 48
/// UInt4     | 16
/// UInt4x2   | 32
/// UInt4x3   | 48
/// UInt4x4   | 64
/// ULong     | 8
/// UShort    | 2
/// </reference>

#pragma warning disable

using EncosyTower.EnumExtensions;

namespace EncosyTower.Entities.Stats
{
    /// <summary>
    /// Represents a collection of supported data sizes, in bytes, to store stat variants.
    /// </summary>
    [EnumExtensions]
    public enum StatDataSize : byte
    {
        /// <summary>
        /// 2 bytes.
        /// </summary>
        Size2 = 2,

        /// <summary>
        /// 4 bytes.
        /// </summary>
        Size4 = 4,

        /// <summary>
        /// 6 bytes.
        /// </summary>
        Size6 = 6,

        /// <summary>
        /// 8 bytes.
        /// </summary>
        Size8 = 8,

        /// <summary>
        /// 12 bytes.
        /// </summary>
        Size12 = 12,

        /// <summary>
        /// 16 bytes.
        /// </summary>
        Size16 = 16,

        /// <summary>
        /// 24 bytes.
        /// </summary>
        Size24 = 24,

        /// <summary>
        /// 32 bytes.
        /// </summary>
        Size32 = 32,

        /// <summary>
        /// 36 bytes.
        /// </summary>
        Size36 = 36,

        /// <summary>
        /// 48 bytes.
        /// </summary>
        Size48 = 48,

        /// <summary>
        /// 64 bytes.
        /// </summary>
        Size64 = 64,

        /// <summary>
        /// 72 bytes.
        /// </summary>
        Size72 = 72,

        /// <summary>
        /// 96 bytes.
        /// </summary>
        Size96 = 96,

        /// <summary>
        /// 128 bytes.
        /// </summary>
        Size128 = 128,

    }

    partial interface IStatDataSizeExtensions { }

    partial struct StatDataSizeExtended { }

    static partial class StatDataSizeExtensions
    {
        partial class DisplayNames { }

        partial class FixedDisplayNames { }

        partial class FixedNames { }

        partial class Names { }

        partial class UnderlyingValues { }

        partial class Values { }

    }

}

