/// <auto-generated>
///*******************************************************************///
///                                                                   ///
/// This file is auto-generated by StatVariantTypeExtensionsGenerator ///
///                    DO NOT manually modify it!                     ///
///                                                                   ///
///*******************************************************************///
/// </auto-generated>

#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;

namespace EncosyTower.Entities.Stats
{
    partial interface IStatVariantTypeExtensions { }

    partial struct StatVariantTypeExtended { }

    static partial class StatVariantTypeExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatVariant ZeroVariant(this StatVariantType type)
            => new(type);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatVariant OneVariant(this StatVariantType type)
        {
            return type switch
            {
                StatVariantType.None => new StatVariant(new None()),
                StatVariantType.Bool => new StatVariant(true),
                StatVariantType.Bool2 => new StatVariant(new bool2(true)),
                StatVariantType.Bool2x2 => new StatVariant(new bool2x2(true)),
                StatVariantType.Bool2x3 => new StatVariant(new bool2x3(true)),
                StatVariantType.Bool2x4 => new StatVariant(new bool2x4(true)),
                StatVariantType.Bool3 => new StatVariant(new bool3(true)),
                StatVariantType.Bool3x2 => new StatVariant(new bool3x2(true)),
                StatVariantType.Bool3x3 => new StatVariant(new bool3x3(true)),
                StatVariantType.Bool3x4 => new StatVariant(new bool3x4(true)),
                StatVariantType.Bool4 => new StatVariant(new bool4(true)),
                StatVariantType.Bool4x2 => new StatVariant(new bool4x2(true)),
                StatVariantType.Bool4x3 => new StatVariant(new bool4x3(true)),
                StatVariantType.Bool4x4 => new StatVariant(new bool4x4(true)),
                StatVariantType.Byte => new StatVariant((byte)1),
                StatVariantType.Double => new StatVariant((double)1.0),
                StatVariantType.Double2 => new StatVariant(new double2(1.0)),
                StatVariantType.Double2x2 => new StatVariant(new double2x2(1.0)),
                StatVariantType.Double2x3 => new StatVariant(new double2x3(1.0)),
                StatVariantType.Double2x4 => new StatVariant(new double2x4(1.0)),
                StatVariantType.Double3 => new StatVariant(new double3(1.0)),
                StatVariantType.Double3x2 => new StatVariant(new double3x2(1.0)),
                StatVariantType.Double3x3 => new StatVariant(new double3x3(1.0)),
                StatVariantType.Double3x4 => new StatVariant(new double3x4(1.0)),
                StatVariantType.Double4 => new StatVariant(new double4(1.0)),
                StatVariantType.Double4x2 => new StatVariant(new double4x2(1.0)),
                StatVariantType.Double4x3 => new StatVariant(new double4x3(1.0)),
                StatVariantType.Double4x4 => new StatVariant(new double4x4(1.0)),
                StatVariantType.Float => new StatVariant((float)1f),
                StatVariantType.Float2 => new StatVariant(new float2(1f)),
                StatVariantType.Float2x2 => new StatVariant(new float2x2(1f)),
                StatVariantType.Float2x3 => new StatVariant(new float2x3(1f)),
                StatVariantType.Float2x4 => new StatVariant(new float2x4(1f)),
                StatVariantType.Float3 => new StatVariant(new float3(1f)),
                StatVariantType.Float3x2 => new StatVariant(new float3x2(1f)),
                StatVariantType.Float3x3 => new StatVariant(new float3x3(1f)),
                StatVariantType.Float3x4 => new StatVariant(new float3x4(1f)),
                StatVariantType.Float4 => new StatVariant(new float4(1f)),
                StatVariantType.Float4x2 => new StatVariant(new float4x2(1f)),
                StatVariantType.Float4x3 => new StatVariant(new float4x3(1f)),
                StatVariantType.Float4x4 => new StatVariant(new float4x4(1f)),
                StatVariantType.Half => new StatVariant(math.half(1f)),
                StatVariantType.Half2 => new StatVariant(math.half2(1f)),
                StatVariantType.Half3 => new StatVariant(math.half3(1f)),
                StatVariantType.Half4 => new StatVariant(math.half4(1f)),
                StatVariantType.Int => new StatVariant((int)1),
                StatVariantType.Int2 => new StatVariant(new int2(1)),
                StatVariantType.Int2x2 => new StatVariant(new int2x2(1)),
                StatVariantType.Int2x3 => new StatVariant(new int2x3(1)),
                StatVariantType.Int2x4 => new StatVariant(new int2x4(1)),
                StatVariantType.Int3 => new StatVariant(new int3(1)),
                StatVariantType.Int3x2 => new StatVariant(new int3x2(1)),
                StatVariantType.Int3x3 => new StatVariant(new int3x3(1)),
                StatVariantType.Int3x4 => new StatVariant(new int3x4(1)),
                StatVariantType.Int4 => new StatVariant(new int4(1)),
                StatVariantType.Int4x2 => new StatVariant(new int4x2(1)),
                StatVariantType.Int4x3 => new StatVariant(new int4x3(1)),
                StatVariantType.Int4x4 => new StatVariant(new int4x4(1)),
                StatVariantType.Long => new StatVariant((long)1),
                StatVariantType.SByte => new StatVariant((sbyte)1),
                StatVariantType.Short => new StatVariant((short)1),
                StatVariantType.UInt => new StatVariant((uint)1),
                StatVariantType.UInt2 => new StatVariant(new uint2((uint)1)),
                StatVariantType.UInt2x2 => new StatVariant(new uint2x2((uint)1)),
                StatVariantType.UInt2x3 => new StatVariant(new uint2x3((uint)1)),
                StatVariantType.UInt2x4 => new StatVariant(new uint2x4((uint)1)),
                StatVariantType.UInt3 => new StatVariant(new uint3((uint)1)),
                StatVariantType.UInt3x2 => new StatVariant(new uint3x2((uint)1)),
                StatVariantType.UInt3x3 => new StatVariant(new uint3x3((uint)1)),
                StatVariantType.UInt3x4 => new StatVariant(new uint3x4((uint)1)),
                StatVariantType.UInt4 => new StatVariant(new uint4((uint)1)),
                StatVariantType.UInt4x2 => new StatVariant(new uint4x2((uint)1)),
                StatVariantType.UInt4x3 => new StatVariant(new uint4x3((uint)1)),
                StatVariantType.UInt4x4 => new StatVariant(new uint4x4((uint)1)),
                StatVariantType.ULong => new StatVariant((ulong)1),
                StatVariantType.UShort => new StatVariant((ushort)1),
                _ => default,
            };
        }

    }

}

