#if UNITY_MATHEMATICS

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To update the generation of this file, modify and re-run Unity.Mathematics.CodeGen.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace Unity.Mathematics
{
    using static Unity.Mathematics.math;

    /// <summary>A 3 component vector of ushorts.</summary>
    [DebuggerTypeProxy(typeof(ushort3.DebuggerProxy))]
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct ushort3 : System.IEquatable<ushort3>, IFormattable
    {
        /// <summary>x component of the vector.</summary>
        public ushort x;
        /// <summary>y component of the vector.</summary>
        public ushort y;
        /// <summary>z component of the vector.</summary>
        public ushort z;


        /// <summary>Constructs a ushort3 vector from three ushort values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <param name="z">The constructed vector's z component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(ushort x, ushort y, ushort z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
        
        /// <summary>Constructs a ushort3 vector from three ushort values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <param name="z">The constructed vector's z component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(int x, int y, int z)
        {
            this.x = (ushort)x;
            this.y = (ushort)y;
            this.z = (ushort)z;
        }

        /// <summary>Constructs a ushort3 vector from a ushort value and a ushort2 vector.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="yz">The constructed vector's yz components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(ushort x, ushort2 yz)
        {
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
        }

        /// <summary>Constructs a ushort3 vector from a ushort2 vector and a ushort value.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <param name="z">The constructed vector's z component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(ushort2 xy, ushort z)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
        }

        /// <summary>Constructs a ushort3 vector from a ushort3 vector.</summary>
        /// <param name="xyz">The constructed vector's xyz components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(ushort3 xyz)
        {
            this.x = xyz.x;
            this.y = xyz.y;
            this.z = xyz.z;
        }

        /// <summary>Constructs a ushort3 vector from a single ushort value by assigning it to every component.</summary>
        /// <param name="v">ushort to convert to ushort3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort3(ushort v)
        {
            this.x = v;
            this.y = v;
            this.z = v;
        }


        /// <summary>Implicitly converts a single ushort value to a ushort3 vector by assigning it to every component.</summary>
        /// <param name="v">ushort to convert to ushort3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ushort3(ushort v) { return new ushort3(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise multiplication.</param>
        /// <returns>ushort3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator * (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z); }

        /// <summary>Returns the result of a componentwise multiplication operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise multiplication.</param>
        /// <returns>ushort3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator * (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x * rhs, lhs.y * rhs, lhs.z * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise multiplication.</param>
        /// <returns>ushort3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator * (ushort lhs, ushort3 rhs) { return new ushort3 (lhs * rhs.x, lhs * rhs.y, lhs * rhs.z); }


        /// <summary>Returns the result of a componentwise addition operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise addition.</param>
        /// <returns>ushort3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator + (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z); }

        /// <summary>Returns the result of a componentwise addition operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise addition.</param>
        /// <returns>ushort3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator + (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x + rhs, lhs.y + rhs, lhs.z + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise addition.</param>
        /// <returns>ushort3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator + (ushort lhs, ushort3 rhs) { return new ushort3 (lhs + rhs.x, lhs + rhs.y, lhs + rhs.z); }


        /// <summary>Returns the result of a componentwise subtraction operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise subtraction.</param>
        /// <returns>ushort3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator - (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z); }

        /// <summary>Returns the result of a componentwise subtraction operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise subtraction.</param>
        /// <returns>ushort3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator - (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x - rhs, lhs.y - rhs, lhs.z - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise subtraction.</param>
        /// <returns>ushort3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator - (ushort lhs, ushort3 rhs) { return new ushort3 (lhs - rhs.x, lhs - rhs.y, lhs - rhs.z); }


        /// <summary>Returns the result of a componentwise division operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise division.</param>
        /// <returns>ushort3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator / (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z); }

        /// <summary>Returns the result of a componentwise division operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise division.</param>
        /// <returns>ushort3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator / (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x / rhs, lhs.y / rhs, lhs.z / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise division.</param>
        /// <returns>ushort3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator / (ushort lhs, ushort3 rhs) { return new ushort3 (lhs / rhs.x, lhs / rhs.y, lhs / rhs.z); }


        /// <summary>Returns the result of a componentwise modulus operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise modulus.</param>
        /// <returns>ushort3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator % (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z); }

        /// <summary>Returns the result of a componentwise modulus operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise modulus.</param>
        /// <returns>ushort3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator % (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x % rhs, lhs.y % rhs, lhs.z % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise modulus.</param>
        /// <returns>ushort3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator % (ushort lhs, ushort3 rhs) { return new ushort3 (lhs % rhs.x, lhs % rhs.y, lhs % rhs.z); }


        /// <summary>Returns the result of a componentwise increment operation on a ushort3 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>ushort3 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator ++ (ushort3 val) { return new ushort3 (++val.x, ++val.y, ++val.z); }


        /// <summary>Returns the result of a componentwise decrement operation on a ushort3 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>ushort3 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator -- (ushort3 val) { return new ushort3 (--val.x, --val.y, --val.z); }


        /// <summary>Returns the result of a componentwise less than operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise less than.</param>
        /// <returns>bool3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }

        /// <summary>Returns the result of a componentwise less than operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise less than.</param>
        /// <returns>bool3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise less than.</param>
        /// <returns>bool3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (ushort lhs, ushort3 rhs) { return new bool3 (lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }


        /// <summary>Returns the result of a componentwise less or equal operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise less or equal.</param>
        /// <returns>bool3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }

        /// <summary>Returns the result of a componentwise less or equal operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise less or equal.</param>
        /// <returns>bool3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise less or equal.</param>
        /// <returns>bool3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (ushort lhs, ushort3 rhs) { return new bool3 (lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }


        /// <summary>Returns the result of a componentwise greater than operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise greater than.</param>
        /// <returns>bool3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }

        /// <summary>Returns the result of a componentwise greater than operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise greater than.</param>
        /// <returns>bool3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise greater than.</param>
        /// <returns>bool3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (ushort lhs, ushort3 rhs) { return new bool3 (lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise greater or equal.</param>
        /// <returns>bool3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise greater or equal.</param>
        /// <returns>bool3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise greater or equal.</param>
        /// <returns>bool3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (ushort lhs, ushort3 rhs) { return new bool3 (lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }


        /// <summary>Returns the result of a componentwise unary minus operation on a ushort3 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>ushort3 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator - (ushort3 val) { return new ushort3 (-val.x, -val.y, -val.z); }


        /// <summary>Returns the result of a componentwise unary plus operation on a ushort3 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>ushort3 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator + (ushort3 val) { return new ushort3 (+val.x, +val.y, +val.z); }


        /// <summary>Returns the result of a componentwise left shift operation on a ushort3 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to left shift.</param>
        /// <param name="n">The number of bits to left shift.</param>
        /// <returns>The result of the componentwise left shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator << (ushort3 x, int n) { return new ushort3 (x.x << n, x.y << n, x.z << n); }

        /// <summary>Returns the result of a componentwise right shift operation on a ushort3 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to right shift.</param>
        /// <param name="n">The number of bits to right shift.</param>
        /// <returns>The result of the componentwise right shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator >> (ushort3 x, int n) { return new ushort3 (x.x >> n, x.y >> n, x.z >> n); }

        /// <summary>Returns the result of a componentwise equality operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise equality.</param>
        /// <returns>bool3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }

        /// <summary>Returns the result of a componentwise equality operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise equality.</param>
        /// <returns>bool3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise equality.</param>
        /// <returns>bool3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (ushort lhs, ushort3 rhs) { return new bool3 (lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }


        /// <summary>Returns the result of a componentwise not equal operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise not equal.</param>
        /// <returns>bool3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (ushort3 lhs, ushort3 rhs) { return new bool3 (lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }

        /// <summary>Returns the result of a componentwise not equal operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise not equal.</param>
        /// <returns>bool3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (ushort3 lhs, ushort rhs) { return new bool3 (lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise not equal.</param>
        /// <returns>bool3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (ushort lhs, ushort3 rhs) { return new bool3 (lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }


        /// <summary>Returns the result of a componentwise bitwise not operation on a ushort3 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise bitwise not.</param>
        /// <returns>ushort3 result of the componentwise bitwise not.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator ~ (ushort3 val) { return new ushort3 (~val.x, ~val.y, ~val.z); }


        /// <summary>Returns the result of a componentwise bitwise and operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise and.</param>
        /// <returns>ushort3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator & (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise bitwise and.</param>
        /// <returns>ushort3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator & (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x & rhs, lhs.y & rhs, lhs.z & rhs); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise and.</param>
        /// <returns>ushort3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator & (ushort lhs, ushort3 rhs) { return new ushort3 (lhs & rhs.x, lhs & rhs.y, lhs & rhs.z); }


        /// <summary>Returns the result of a componentwise bitwise or operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise or.</param>
        /// <returns>ushort3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator | (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise bitwise or.</param>
        /// <returns>ushort3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator | (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x | rhs, lhs.y | rhs, lhs.z | rhs); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise or.</param>
        /// <returns>ushort3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator | (ushort lhs, ushort3 rhs) { return new ushort3 (lhs | rhs.x, lhs | rhs.y, lhs | rhs.z); }


        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on two ushort3 vectors.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>ushort3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator ^ (ushort3 lhs, ushort3 rhs) { return new ushort3 (lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a ushort3 vector and a ushort value.</summary>
        /// <param name="lhs">Left hand side ushort3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side ushort to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>ushort3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator ^ (ushort3 lhs, ushort rhs) { return new ushort3 (lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a ushort value and a ushort3 vector.</summary>
        /// <param name="lhs">Left hand side ushort to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side ushort3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>ushort3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 operator ^ (ushort lhs, ushort3 rhs) { return new ushort3 (lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z); }




        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, x, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, y, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 xzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(x, z, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, x, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, y, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 yzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(y, z, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, x, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, y, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort4 zzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort4(z, z, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, y, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; z = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, z, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; z = value.y; y = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 xzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(x, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, x, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; z = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, z, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; z = value.y; x = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 yzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(y, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; x = value.y; y = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, x, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; y = value.y; x = value.z; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, y, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, z, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, z, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort3 zzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort3(z, z, z); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 xz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(x, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; z = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 yz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(y, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; z = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 zx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(z, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 zy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(z, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ushort2 zz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ushort2(z, z); }
        }



        /// <summary>Returns the ushort element at a specified index.</summary>
        unsafe public ushort this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (ushort3* array = &this) { return ((ushort*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (ushort* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the ushort3 is equal to a given ushort3, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(ushort3 rhs) { return x == rhs.x && y == rhs.y && z == rhs.z; }

        /// <summary>Returns true if the ushort3 is equal to a given ushort3, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is ushort3 converted && Equals(converted); }


        /// <summary>Returns a hash code for the ushort3.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)umath.hash(this); }


        /// <summary>Returns a string representation of the ushort3.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("ushort3({0}, {1}, {2})", x, y, z);
        }

        /// <summary>Returns a string representation of the ushort3 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("ushort3({0}, {1}, {2})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public ushort x;
            public ushort y;
            public ushort z;
            public DebuggerProxy(ushort3 v)
            {
                x = v.x;
                y = v.y;
                z = v.z;
            }
        }

    }

    public static partial class umath
    {
        /// <summary>Returns a ushort3 vector constructed from three ushort values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <param name="z">The constructed vector's z component will be set to this value.</param>
        /// <returns>ushort3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 ushort3(ushort x, ushort y, ushort z) { return new ushort3(x, y, z); }

        /// <summary>Returns a ushort3 vector constructed from a ushort value and a ushort2 vector.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="yz">The constructed vector's yz components will be set to this value.</param>
        /// <returns>ushort3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 ushort3(ushort x, ushort2 yz) { return new ushort3(x, yz); }

        /// <summary>Returns a ushort3 vector constructed from a ushort2 vector and a ushort value.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <param name="z">The constructed vector's z component will be set to this value.</param>
        /// <returns>ushort3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 ushort3(ushort2 xy, ushort z) { return new ushort3(xy, z); }

        /// <summary>Returns a ushort3 vector constructed from a ushort3 vector.</summary>
        /// <param name="xyz">The constructed vector's xyz components will be set to this value.</param>
        /// <returns>ushort3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 ushort3(ushort3 xyz) { return new ushort3(xyz); }

        /// <summary>Returns a ushort3 vector constructed from a single ushort value by assigning it to every component.</summary>
        /// <param name="v">ushort to convert to ushort3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 ushort3(ushort v) { return new ushort3(v); }

        /// <summary>Returns a uint hash code of a ushort3 vector.</summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(ushort3 v)
        {
            return csum(asuint(v) * uint3(0xE857DCE1u, 0xF62213C5u, 0x9CDAA959u)) + 0xAA269ABFu;
        }

        /// <summary>
        /// Returns a uint3 vector hash code of a ushort3 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint3 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint3 hashwide(ushort3 v)
        {
            return (asuint(v) * uint3(0xD54BA36Fu, 0xFD0847B9u, 0x8189A683u)) + 0xB139D651u;
        }

        /// <summary>Returns the result of specified shuffling of the components from two ushort3 vectors into a ushort value.</summary>
        /// <param name="left">ushort3 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">ushort3 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting ushort.</param>
        /// <returns>ushort result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort shuffle(ushort3 left, ushort3 right, ShuffleComponent x)
        {
            return select_shuffle_component(left, right, x);
        }

        /// <summary>Returns the result of specified shuffling of the components from two ushort3 vectors into a ushort2 vector.</summary>
        /// <param name="left">ushort3 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">ushort3 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting ushort2 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting ushort2 y component.</param>
        /// <returns>ushort2 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort2 shuffle(ushort3 left, ushort3 right, ShuffleComponent x, ShuffleComponent y)
        {
            return ushort2(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y));
        }

        /// <summary>Returns the result of specified shuffling of the components from two ushort3 vectors into a ushort3 vector.</summary>
        /// <param name="left">ushort3 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">ushort3 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting ushort3 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting ushort3 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting ushort3 z component.</param>
        /// <returns>ushort3 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort3 shuffle(ushort3 left, ushort3 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z)
        {
            return ushort3(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z));
        }

        /// <summary>Returns the result of specified shuffling of the components from two ushort3 vectors into a ushort4 vector.</summary>
        /// <param name="left">ushort3 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">ushort3 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting ushort4 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting ushort4 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting ushort4 z component.</param>
        /// <param name="w">The ShuffleComponent to use when setting the resulting ushort4 w component.</param>
        /// <returns>ushort4 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort4 shuffle(ushort3 left, ushort3 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z, ShuffleComponent w)
        {
            return ushort4(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z),
                select_shuffle_component(left, right, w));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ushort select_shuffle_component(ushort3 a, ushort3 b, ShuffleComponent component)
        {
            switch(component)
            {
                case ShuffleComponent.LeftX:
                    return a.x;
                case ShuffleComponent.LeftY:
                    return a.y;
                case ShuffleComponent.LeftZ:
                    return a.z;
                case ShuffleComponent.RightX:
                    return b.x;
                case ShuffleComponent.RightY:
                    return b.y;
                case ShuffleComponent.RightZ:
                    return b.z;
                default:
                    throw new System.ArgumentException("Invalid shuffle component: " + component);
            }
        }

    }
}

#endif
