#if UNITY_EDITOR && ANNULUS_CODEGEN && ENCOSY_STAT_VALUE_TYPES_GENERATOR

using System;
using System.Collections.Generic;
using System.Linq;
using EncosyTower.CodeGen;
using UnityCodeGen;

namespace EncosyTower.Entities.Stats.Generators
{
    [Generator]
    internal sealed class StatDataSizeGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatDataSizeGenerator));
            p.PrintEndLine();
            
            WriteReferenceBlock(ref p);

            p.PrintLine(@"#pragma warning disable

using EncosyTower.EnumExtensions;
");

            p.PrintLine("namespace EncosyTower.Entities.Stats");
            p.OpenScope();
            {
                var uniqueSizes = new HashSet<int>(GeneratorAPI.Sizes);
                var sizes = uniqueSizes.Select(static x => x).OrderBy(static x => x).ToArray().AsSpan();

                p.PrintLine("/// <summary>");
                p.PrintLine("/// Represents a collection of supported data sizes, in bytes, to store stat variants.");
                p.PrintLine("/// </summary>");
                p.PrintLine("[EnumExtensions]");
                p.PrintLine("public enum StatDataSize : byte");
                p.OpenScope();
                {
                    for (var i = 0; i < sizes.Length; i++)
                    {
                        var size = sizes[i];

                        if (size % 2 != 0)
                        {
                            continue;
                        }

                        p.PrintLine("/// <summary>");
                        p.PrintBeginLine("/// ").Print(size).PrintEndLineSelect(" bytes.", " byte.", size > 1);
                        p.PrintLine("/// </summary>");
                        p.PrintBeginLine("Size").Print(size).Print(" = ").Print(size).PrintEndLine(",");
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine("partial interface IStatDataSizeExtensions { }");
                p.PrintEndLine();

                p.PrintLine("partial struct StatDataSizeExtended { }");
                p.PrintEndLine();

                p.PrintLine("static partial class StatDataSizeExtensions");
                p.OpenScope();
                {
                    p.PrintLine("partial class DisplayNames { }");
                    p.PrintEndLine();
                    
                    p.PrintLine("partial class FixedDisplayNames { }");
                    p.PrintEndLine();
                    
                    p.PrintLine("partial class FixedNames { }");
                    p.PrintEndLine();
                    
                    p.PrintLine("partial class Names { }");
                    p.PrintEndLine();
                    
                    p.PrintLine("partial class UnderlyingValues { }");
                    p.PrintEndLine();
                    
                    p.PrintLine("partial class Values { }");
                    p.PrintEndLine();
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: GeneratorAPI.COMMON_FOLDER));
            context.AddCode($"StatDataSize.gen.cs", p.Result);
        }

        private static void WriteReferenceBlock(ref Printer p)
        {
            var sizes = GeneratorAPI.Sizes.AsSpan();
            var typeNames = GeneratorAPI.TypeNames.AsSpan();
            var maxLength = GeneratorAPI.TypeNames.Select(static x => x.Length).OrderBy(static x => x).Max();
            var pad4 = maxLength - 4;

            p.PrintBeginLine("/// ").PrintEndLine("<reference>");
            p.PrintBeginLine("/// ").PrintEndLine("LIST OF SUPPORTED TYPES AND THEIR SIZE");
            p.PrintBeginLine("/// ").Print("TYPE").Print(' ', pad4).Print(" | SIZE (bytes)").PrintEndLine();
            p.PrintBeginLine("/// ").Print('-', maxLength).Print(" | ------------").PrintEndLine();

            for (var i = 0; i < sizes.Length; i++)
            {
                var size = sizes[i];
                var typeName = typeNames[i];
                var pad = maxLength - typeName.Length;

                p.PrintBeginLine("/// ").Print(typeName).Print(' ', pad).Print(" | ").Print(size).PrintEndLine();
            }

            p.PrintBeginLine("/// ").PrintEndLine("</reference>");
            p.PrintEndLine();

        }
    }
}

#endif
