#if UNITY_EDITOR && ANNULUS_CODEGEN && ENCOSY_STAT_VALUE_TYPES_GENERATOR

using System;
using EncosyTower.CodeGen;
using UnityCodeGen;

namespace EncosyTower.Entities.Stats.Generators
{
    [Generator]
    internal sealed class StatVariantTypeExtensionsGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatVariantTypeExtensionsGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;
");

            p.PrintLine("namespace EncosyTower.Entities.Stats");
            p.OpenScope();
            {
                var typeNames = GeneratorAPI.TypeNames.AsSpan();
                var oneConstructors = GeneratorAPI.OneConstructors.AsSpan();

                p.PrintLine("partial interface IStatVariantTypeExtensions { }");
                p.PrintEndLine();

                p.PrintLine("partial struct StatVariantTypeExtended { }");
                p.PrintEndLine();

                p.PrintLine("static partial class StatVariantTypeExtensions");
                p.OpenScope();
                {
                    p.PrintLine(GeneratorAPI.AGGRESSIVE_INLINING);
                    p.PrintLine("public static StatVariant ZeroVariant(this StatVariantType type)");
                    p.WithIncreasedIndent().PrintLine("=> new(type);");
                    p.PrintEndLine();

                    p.PrintLine(GeneratorAPI.AGGRESSIVE_INLINING);
                    p.PrintLine("public static StatVariant OneVariant(this StatVariantType type)");
                    p.OpenScope();
                    {
                        p.PrintLine("return type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < typeNames.Length; i++)
                            {
                                var typeName = typeNames[i];
                                var oneConstructor = oneConstructors[i];

                                p.PrintBeginLine("StatVariantType.").Print(typeName)
                                    .Print(" => new StatVariant(")
                                    .Print(oneConstructor)
                                    .PrintEndLine("),");
                            }

                            p.PrintLine("_ => default,");
                        }
                        p.CloseScope("};");
                    }
                    p.CloseScope();
                    p.PrintEndLine();
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: GeneratorAPI.COMMON_FOLDER));
            context.AddCode($"StatVariantTypeExtensions.gen.cs", p.Result);
        }
    }
}

#endif
