/// <auto-generated>
///***********************************************************///
///                                                           ///
/// This file is auto-generated by AnyToLongAdaptersGenerator ///
///                DO NOT manually modify it!                 ///
///                                                           ///
///***********************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants;

namespace EncosyTower.Mvvm.ViewBinding.Adapters
{
    [Serializable]
    [Label("Byte ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(byte), destType: typeof(long), order: 0)]
    public sealed class ByteToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out byte result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("SByte ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(sbyte), destType: typeof(long), order: 0)]
    public sealed class SByteToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out sbyte result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Char ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(char), destType: typeof(long), order: 0)]
    public sealed class CharToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out char result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Double ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(double), destType: typeof(long), order: 0)]
    public sealed class DoubleToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out double result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Float ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(float), destType: typeof(long), order: 0)]
    public sealed class FloatToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out float result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Int ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(int), destType: typeof(long), order: 0)]
    public sealed class IntToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out int result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("UInt ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(uint), destType: typeof(long), order: 0)]
    public sealed class UIntToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out uint result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Long ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(long), destType: typeof(long), order: 0)]
    public sealed class LongToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out long result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("ULong ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(ulong), destType: typeof(long), order: 0)]
    public sealed class ULongToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ulong result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("Short ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(short), destType: typeof(long), order: 0)]
    public sealed class ShortToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out short result))
            {
                return (long)result;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("UShort ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(ushort), destType: typeof(long), order: 0)]
    public sealed class UShortToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ushort result))
            {
                return (long)result;
            }

            return variant;
        }
    }

}

