#if UNITY_EDITOR && ANNULUS_CODEGEN && ENCOSY_MVVM_ADAPTERS_GENERATOR

using System;
using EncosyTower.CodeGen;
using EncosyTower.Common;
using UnityCodeGen;

namespace EncosyTower.Editor.Mvvm.Variants.Converters
{
    internal abstract class ConvertibleToAnyAdaptersGenerator : ICodeGenerator
    {
        private static readonly string[] s_variantTypes = new string[] {
            "byte",
            "sbyte",
            "char",
            "double",
            "float",
            "int",
            "uint",
            "long",
            "ulong",
            "short",
            "ushort",
        };

        private static readonly string[] s_variantTypeNames = new string[] {
            "Byte",
            "SByte",
            "Char",
            "Double",
            "Float",
            "Int",
            "UInt",
            "Long",
            "ULong",
            "Short",
            "UShort",
        };

        protected abstract string FromType { get; }

        protected abstract string FromTypeName { get; }

        protected abstract string FileName { get; }

        protected virtual int Order => 0;

        protected virtual string GetReturnExpression(string type)
        {
            return "value";
        }

        protected virtual string GetConditionalExpression(string type)
        {
            return string.Empty;
        }

        public void Execute(GeneratorContext context)
        {
            if (CodeGenAPI.TryGetOutputFolderPath(nameof(ConvertibleToAnyAdaptersGenerator), out var outputPath) == false)
            {
                context.OverrideFolderPath("Assets");
                return;
            }

            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(GetType().Name);
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants;
");

            p.PrintLine("namespace EncosyTower.Mvvm.ViewBinding.Adapters");
            p.OpenScope();
            {
                var variantTypes = s_variantTypes.AsSpan();
                var variantTypeNames = s_variantTypeNames.AsSpan();
                var fromType = FromType;
                var fromTypeName = FromTypeName;
                var order = Order.ToString();

                for (var i = 0; i < variantTypes.Length; i++)
                {
                    var toType = variantTypes[i];
                    var toTypeName = variantTypeNames[i];
                    var conditionExpression = GetConditionalExpression(toType);
                    var returnStatement = GetReturnExpression(toType);

                    p.PrintLine("[Serializable]");
                    p.PrintBeginLine("[Label(\"").Print(fromTypeName).Print(" ⇒ ")
                        .Print(toTypeName).PrintEndLine("\", \"Default\")]");
                    p.PrintBeginLine("[Adapter(sourceType: typeof(").Print(fromType)
                        .Print("), destType: typeof(").Print(toType)
                        .Print("), order: ").Print(order).PrintEndLine(")]");
                    p.PrintBeginLine("public sealed class ").Print(fromTypeName)
                        .Print("To").Print(toTypeName)
                        .PrintEndLine("Adapter : IAdapter");
                    p.OpenScope();
                    {
                        p.PrintLine("public Variant Convert(in Variant variant)");
                        p.OpenScope();
                        {
                            p.PrintBeginLine("if (variant.TryGetValue(out ").Print(fromType).Print(" result)");

                            if (conditionExpression.IsNotEmpty())
                            {
                                p.PrintEndLine().WithIncreasedIndent()
                                    .PrintBeginLine(conditionExpression).PrintEndLine();
                                p.PrintLine(")");
                            }
                            else
                            {
                                p.PrintEndLine(")");
                            }

                            p.OpenScope();
                            {
                                p.PrintBeginLine("return ").Print(returnStatement).PrintEndLine(";");
                            }
                            p.CloseScope();
                            p.PrintEndLine();

                            p.PrintLine("return variant;");
                        }
                        p.CloseScope();
                    }
                    p.CloseScope();
                    p.PrintEndLine();
                }
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(outputPath);
            context.AddCode($"{FileName}.gen.cs", p.Result);
        }
    }

    [Generator]
    internal sealed class BoolToAnyAdaptersGenerator : ConvertibleToAnyAdaptersGenerator
    {
        protected override string FromType => "bool";

        protected override string FromTypeName => "Bool";

        protected override string FileName => "BoolToAnyAdapters";

        protected override string GetReturnExpression(string type)
        {
            return $"({type})(result ? 1 : 0)";
        }
    }

    [Generator]
    internal sealed class StringToAnyAdaptersGenerator : ConvertibleToAnyAdaptersGenerator
    {
        protected override string FromType => "string";

        protected override string FromTypeName => "String";

        protected override string FileName => "StringToAnyAdapters";

        protected override string GetConditionalExpression(string type)
        {
            return $"&& {type}.TryParse(result, out var value)";
        }
    }

    [Generator]
    internal sealed class ObjectToAnyAdaptersGenerator : ConvertibleToAnyAdaptersGenerator
    {
        protected override string FromType => "object";

        protected override string FromTypeName => "Object";

        protected override string FileName => "ObjectToAnyAdapters";

        protected override string GetConditionalExpression(string type)
        {
            return $"&& result is {type} value";
        }
    }
}

#endif
