/// <auto-generated>
///*************************************************************///
///                                                             ///
/// This file is auto-generated by StringToAnyAdaptersGenerator ///
///                 DO NOT manually modify it!                  ///
///                                                             ///
///*************************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants;

namespace EncosyTower.Mvvm.ViewBinding.Adapters
{
    [Serializable]
    [Label("String ⇒ Byte", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(byte), order: 0)]
    public sealed class StringToByteAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && byte.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ SByte", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(sbyte), order: 0)]
    public sealed class StringToSByteAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && sbyte.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Char", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(char), order: 0)]
    public sealed class StringToCharAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && char.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Double", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(double), order: 0)]
    public sealed class StringToDoubleAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && double.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Float", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(float), order: 0)]
    public sealed class StringToFloatAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && float.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Int", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(int), order: 0)]
    public sealed class StringToIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && int.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(uint), order: 0)]
    public sealed class StringToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && uint.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Long", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(long), order: 0)]
    public sealed class StringToLongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && long.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(ulong), order: 0)]
    public sealed class StringToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && ulong.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ Short", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(short), order: 0)]
    public sealed class StringToShortAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && short.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

    [Serializable]
    [Label("String ⇒ UShort", "Default")]
    [Adapter(sourceType: typeof(string), destType: typeof(ushort), order: 0)]
    public sealed class StringToUShortAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out string result)
                && ushort.TryParse(result, out var value)
            )
            {
                return value;
            }

            return variant;
        }
    }

}

