using System.Collections.Generic;

namespace Module.Core.Mvvm.ComponentModel
{
    /// <summary>
    /// Any class implements this interface will be an eligible
    /// candidate to have its details generated by the corresponding generators.
    /// </summary>
    /// <seealso cref="Module.Core.Mvvm.ComponentModel.ObservablePropertyAttribute"/>
    /// <seealso cref="Module.Core.Mvvm.Input.RelayCommandAttribute"/>
    public interface IObservableObject
    {
        bool TryGetMemberObservableObject(Queue<string> names, out IObservableObject result);
    }
}
